insonmnia/miner/overseer.go
This commit fixes use a response variable after returning error.
Found by @antmat. Annoying for me.
=> fix: do not use a nil variable

cmd/cli/main.go, vendor/github.com/dustin/go-humanize/LICENSE, vendor/github.com/dustin/go-humanize/README.markdown, vendor/github.com/dustin/go-humanize/big.go, vendor/github.com/dustin/go-humanize/bigbytes.go, vendor/github.com/dustin/go-humanize/bytes.go, vendor/github.com/dustin/go-humanize/comma.go, vendor/github.com/dustin/go-humanize/commaf.go, vendor/github.com/dustin/go-humanize/ftoa.go, vendor/github.com/dustin/go-humanize/humanize.go, vendor/github.com/dustin/go-humanize/number.go, vendor/github.com/dustin/go-humanize/ordinals.go, vendor/github.com/dustin/go-humanize/si.go, vendor/github.com/dustin/go-humanize/times.go, vendor/vendor.json
This PR fixes fraction truncating, while displaying total RAM consumed by a task. Also it automatically changes units to properly show memory consumption in bytes, kilobytes, megabytes etc.
However in JSON output (#34) it is better to display in bytes.
cc @sshaman1101
=> feat: nice RAM output

cmd/hub/main.go, hub.yaml, insonmnia/hub/config.go, insonmnia/hub/config_test.go, insonmnia/hub/server.go, insonmnia/logging/logging.go, insonmnia/miner/server.go
Preparation for Hub testing with handshakes and other.
Changed:
- Hierarchical hub config.
- Add comments to the default hub config.
- Configure logging in main instead of server.
- Renamed `logger` package to `logging` to avoid naming conflicts.
=> refactor: hierarchical hub config

insonmnia/miner/server.go
This PR makes info logging in miner consistent with the similar ones in hub. See [this](https://github.com/sonm-io/core/pull/36/commits/3c48081613fa7d3f68bada2f372dfd9b2f2b7230).
Includes some chained previous PRs. When merged closes #32 and closes #33.
=> refactor: consistent info logs

cmd/miner/main.go
This commit fixes accidentally removed logger initialization in miner. For consistency with a Hub it is created in the main and assigned to the context.
Logger is not a part of a Hub construction, so this decomposition is more proper.
=> fix: create miner logger again

insonmnia/miner/server.go
This fixes meaningless hanging when unable to discover hubs.
cc @Sokel @noxiouz
=> fix: use discovery on demand

insonmnia/hub/server.go, insonmnia/miner/server.go
GRPC provides its own detached context, so using it emits default logging configuration.
This commit fixes that behavior by using our context with preconfigured logging.
=> fix: use proper context for logging RPC

.gitignore
Mock files are not the subject of the repository, because we generate them on the fly.
=> chore: update ignored files list

insonmnia/miner/builder.go, insonmnia/miner/overseer.go, insonmnia/miner/server.go, insonmnia/miner/server_test.go, insonmnia/resource/pool.go, insonmnia/resource/resource.go
This commit activages self resource control on a miner, disallowing it
to start new tasks if its resources are exhausted. On stop these
allocated resources are freed.
```bash
esafronov@5:~/go/src/github.com/sonm-io/core|master⚡
⇒  ./sonmcli miner list --addr="[::]:10001"
Miner: 127.0.0.1:56905
Miner is idle
esafronov@5:~/go/src/github.com/sonm-io/core|master⚡
⇒  ./sonmcli task start "127.0.0.1:56905" cocaine/cocaine-core --addr="[::]:10001"
Starting "cocaine/cocaine-core" on miner 127.0.0.1:56905...
ID 31afe394-cc14-4a45-84b1-5536c70cb21c, Endpoint [10053/tcp->5.255.232.237:32778]
esafronov@5:~/go/src/github.com/sonm-io/core|master⚡
⇒  ./sonmcli miner list --addr="[::]:10001"
Miner: 127.0.0.1:56905
Tasks:
1) 31afe394-cc14-4a45-84b1-5536c70cb21c
...
>>> Start until no more free cores left. …
```
=> feat: self resource control on miner

cmd/miner/main.go, insonmnia/miner/builder.go
Config is mandatory for builder, also we need to pass param in main when creating server
=> fix: MinerBuilder mandatory param + pass context in main

Makefile, blockchain/Makefile
This uses `make`'s dependency tracking mechanisms to prevent unnecessary rebuildings in blockchain directory.
=> Prevent useless blockchain rebuilds

Makefile, appveyor.yml
Now `make build/miner GPU_SUPPORT=true` builds a miner with suddenly GPU support.
=> feat: Makefile reformat + optional CL activation

insonmnia/miner/builder.go, insonmnia/miner/server.go, vendor/github.com/ccding/go-stun/LICENSE, vendor/github.com/ccding/go-stun/README.md, vendor/github.com/ccding/go-stun/main.go, vendor/github.com/ccding/go-stun/stun/attribute.go, vendor/github.com/ccding/go-stun/stun/client.go, vendor/github.com/ccding/go-stun/stun/const.go, vendor/github.com/ccding/go-stun/stun/discover.go, vendor/github.com/ccding/go-stun/stun/doc.go, vendor/github.com/ccding/go-stun/stun/host.go, vendor/github.com/ccding/go-stun/stun/log.go, vendor/github.com/ccding/go-stun/stun/net.go, vendor/github.com/ccding/go-stun/stun/packet.go, vendor/github.com/ccding/go-stun/stun/response.go, vendor/github.com/ccding/go-stun/stun/tests.go, vendor/github.com/ccding/go-stun/stun/utils.go, vendor/vendor.json
This commit activates automatic NAT discovery using STUN protocol during miner startup. This is planned to be used to bypass NAT restrictions to make miners available from the private networks.
Unfortunately, NAT detection may take a long. It's about 20-30 seconds taken to check all available NAT types, but it's pretty precise.
=> feat: NAT type detection

insonmnia/gateway/gateway_linux.go, insonmnia/gateway/metrics.go, insonmnia/hub/miner_ctx.go, insonmnia/hub/router.go, insonmnia/hub/router_linux.go, insonmnia/hub/router_nonlinux.go
This commit allows to collect virtual services statistics for further traffic accouting.
All requests that are redirected through the gateway consumes network, which is the limited resource for us. Collecting bytes transmitted and received as like as the number of connections consumed allows to properly calculate how much a specific miner affects our network.
There are separate metrics for a specific miner, allowing us to gain statistics for each miner connected (still cleared after disconnection).
Dead virtual services does not clear their accounted traffic consumed.
=> feat: virtual services statistics

insonmnia/hub/server.go, util/util.go, util/util_test.go
This PR fixes invalid address assigning for Fusrodah server.
Happens only if set ip+port for Hub, in that case, discovery responses looks like `213.159.214.60213.159.214.60:10001`
=> fix: parse port from endpoint string

Makefile
This PR fixes go build tag assigning if `GPU_SUPPORT` flag is set.
`go help build` says:
```
-tags 'tag list'
a list of build tags to consider satisfied during the build.
For more information about build tags, see the description of
build constraints in the documentation for the go/build package.
```
But for now, we assigning multiple `-tags ...` flags on a build.
=> fix: set go build tags correctly

vendor/github.com/hashicorp/consul/testutil/server.go
this is a hotfix of https://github.com/sonm-io/core/issues/141, however I think we need to run consul programmatically in this case.
=> fix: do not use testing retrier in consul

insonmnia/hub/server.go
When there are no miners left this will return proper error instead of returning nil pointer.
=> fix: properly detect filtered out miners

cmd/cli/commands/hub.go, insonmnia/hub/acl.go, insonmnia/hub/server.go, vendor/vendor.json
This PR implements worker ACL registration/deregistration.
Added:
- ACL storage on the Hub.
- New CLI commands: `acl register CREDENTIALS` and `acl deregister CREDENTIALS`.
Changed:
- Implemented above methods on the Hub.
Things to be done:
- Waiting for #154, since from there we can extract worker credentials from the certificate and to perform validation while establishing a worker connection.
=> feat: worker ACL

cmd/cli/commands/hub.go, cmd/cli/commands/login.go, cmd/cli/commands/node_acl.go
This PR removes duplicate implementation of ACL section into the CLI.
`wrapHubCommand` func left untouched, need to improve and reuse it.
=> refactor: remove accidentally duplicated code

Makefile, accounts/keys.go, cmd/cli/commands/common.go, cmd/cli/commands/login.go, cmd/cli/config/config.go, cmd/cli/config/config_test.go, cmd/node/main.go, insonmnia/node/market.go, insonmnia/node/server.go, node.yaml
This PR allows a user to load Etherum keys for Node. Key loading implemented in the same way as it was done for cli (#170).
Also, a lot of code from #170 was refactored and reused. And may be reused for Hub's key loading.
=> Feature: node load keys

insonmnia/hub/miner_ctx.go, insonmnia/hub/server.go, miner.yaml
At last workers ACL are used.
It's also possible to run hub/miner in insecure mode as before by setting GRPC_INSECURE enrironment variable.
There are four possible cases:
- Hub insecure, miner insecure -> everything as it was before.
- Hub secure, miner insecure -> hub rejects connection.
- Hub insecure, miner secure -> framing error while connecting.
- Hub secure, miner secure -> wallet check.
=> feat: worker authorization

insonmnia/miner/builder.go, insonmnia/miner/cgroup_test.go, insonmnia/miner/config.go, insonmnia/miner/config_test.go, insonmnia/miner/crypto.go, insonmnia/miner/server_test.go, miner.yaml
This commit activates worker-side Hub authorization using specified wallet key as a Hub endpoint. This wallet is compared with signed-one provided by a Hub during TLS handshake, verifying that we've connected to the proper Hub.
It is also planned to be used for discovery through the Locator, but for now a Hub address must also be specified. The result hub endpoint format is <ethAddr>@<socketAddr>.
This commit also makes hub settings required. I have no idea what to do with whisper at worker's side, but it seems that it can be safely removed.
=> feat: worker-side Hub authorization

insonmnia/hub/cluster.go, insonmnia/hub/server.go
This PR loads all synchronizable entities before hub startup to prevent races.
@noxiouz PTAL
=> feat: preload entities from cluster

insonmnia/hub/cluster.go, insonmnia/hub/server.go
subj. On WatchTree consul can return values with nil data, this is AFAIK related to ttl mechanism in consul.
=> fix: slightly better logging

insonmnia/hub/cluster.go
Small PRs as @3Hren requested  :)
this PR discards all broken endpoints due to blocking connections. Previous behaviour did not return error resulting in malfunctioning client
=> fix: blocking grpc leader connection for straight error detection

insonmnia/hub/cluster.go
Initialises store with appropriate SynchronizableEntitiesPrefix. Compound prefixes (e.g., "/a/b/c" are allowed). Tested with boltdb and consul store backends.
=> fix: create store prefix if necessary

util/certs.go
This PR disable logs from the `util` package shown when using this package into CLI.
Each debugging line with `start certificate rotation loop...` is breaking valid JSON output for CLI.
=> chore: change util's log-level to Debug

Makefile, fusrodah/examples/hub/main.go, fusrodah/hub/server_test.go, fusrodah/miner/server_test.go, insonmnia/gateway/pool.go, insonmnia/gateway/pool_test.go, insonmnia/hub/router_nonlinux.go, insonmnia/resource/pool.go, insonmnia/structs/common.go
it's rather strange that make install builds insomnia, but do not build marketplace and locator.
This PR fixes this and failure in case of missing GOPATH var
=> fix: better makefile install rule

cmd/cli/commands/common.go, cmd/cli/commands/interactor.go, cmd/cli/commands/node_tasks.go, insonmnia/hub/acl.go, insonmnia/hub/acl_test.go, insonmnia/hub/server.go, util/grpcsecure.go
The entire task API now requires wallet authentication.
When a deal is accepted a new auth rule is created at the Hub. For such deal only clients with proper auth info can start tasks, stop them etc.
Technically this is done using per-call authorization options, which requires wallet information passing through.
The wallet itself is self-signed using private key at the client side. The server can verify passed signed wallet to ensure that no one else will stop for example other tasks.
=> feat: entire task API authorization & authentication

cmd/miner/main.go, insonmnia/miner/builder.go, insonmnia/miner/cgroup_test.go, insonmnia/miner/config.go, insonmnia/miner/config_test.go, insonmnia/miner/server.go, insonmnia/miner/server_test.go, miner.yaml, util/grpcsecure.go
* If hub's address is just an ethereum addr, miner looks up hub's addr via locator.
* Addresses returned by locator are checked for reachability, the first reachable address is used.
=> feat: miner resolves hub addr via locator

insonmnia/hub/eth.go, insonmnia/hub/server.go, insonmnia/node/market.go, insonmnia/node/market_test.go, insonmnia/node/server.go
Chained with #278, #284.
This PR fixes an opened and an approved deal selection. 
Changed: 
- Using sync deal creation method (added in #281) to get a created deal ID on the Node;
- Reverse the deals traversal on Hub (newest first);
=> Fix: opened and approved deal selection

insonmnia/hub/eth.go, insonmnia/hub/server.go, insonmnia/structs/order.go
Changed:
- Closing a deal using blockchain API when it expires at Hub-side.
Fixed:
- Releasing resources after deal closing/expiration.
Closes DEV-189, DEV-258.
=> refactor: deal lifecycle

util/grpcsecure.go
Before:
```
2017-12-23T17:02:16.041+0300	ERROR	node/server.go:151	cannot restart order processing	{"error": "rpc error: code = Internal desc = connection error: desc = \"transport: authentication handshake failed: authorization failed: expected \\x81%r\\x1c$\\x13ٚ3\\xe3Q\\xe1\\xf6\\xbbNV\\xb6\\xb63\\xfd, actual s1\\x93\\xd4\\vo\\x03\\xc3\\xda3۲\\xe0\\xe0p\\xac\\xbb\\xf8\\xd9\\x1b\""}
```
After:
```
2017-12-23T17:05:07.210+0300	ERROR	node/server.go:151	cannot restart order processing	{"error": "rpc error: code = Internal desc = connection error: desc = \"transport: authentication handshake failed: authorization failed: expected 0x8125721C2413d99a33E351e1F6Bb4e56b6b633FD, actual 0x733193d40B6F03c3da33Dbb2e0e070aCbBf8d91b\""}
```
=> fix: avoid printing bytes

insonmnia/hub/cluster.go
Fallback to get available IPs if Hub configuration has 0.0.0.0, :: endpoint
=> fix: do not directly announce Hub's IP if it's unspecified

insonmnia/hub/server.go, insonmnia/hub/task_info.go
Fixed:
- Fill all fields in a deal meta info after accepting a deal to be able to properly synchronize.
=> fix: fill all fields in a deal meta struct

insonmnia/node/tasks.go
Do not fail the method call if the Hub cannot be resolved or cannot be reached via the gRPC;
Fixes DEV-273;
=> fix: task list

accounts/identity.go
this PR removes the keystore's scheme parsing and uses the ".Path" field from an account.
The main reason to do this: now it works on Windows!
=> fix: keystore path

cmd/cli/commands/common.go, cmd/cli/commands/version.go
Usage: 
```
sonmcli completion bash > completion.sh
. ./completion.sh
sonmcli [tab]
approve     completion  deals       get         hub         login       market      tasks       version
```
=> aux: add autocomplete for the sonmcli

cmd/cli/commands/common.go, cmd/cli/commands/tasks.go, insonmnia/auth/auth.go, insonmnia/auth/common.go, insonmnia/auth/common_test.go, insonmnia/hub/acl.go, insonmnia/hub/acl_test.go, insonmnia/hub/server.go, insonmnia/hub/whitelist.go, insonmnia/hub/whitelist_test.go, util/grpcsecure.go, util/util.go, util/util_test.go, util/xgrpc/options.go
This PR introduces new way to configure server authorization through chained interceptor middlewares. Things that can be configured:
- Global prefix.
- Fallback logic for unregistered events (allow/deny).
- Custom authorization for specific events.
- Predefined helpers, such as checking for specific transport credentials. 
For example:
```go
authorization := auth.NewEventAuthorization(h.ctx,
auth.WithLog(log.G(ctx)),
auth.WithEventPrefix(hubAPIPrefix),
auth.Allow("Handshake", "ProposeDeal").With(auth.NewNilAuthorization()),
auth.Allow(hubManagementMethods...).With(auth.NewTransportAuthorization(h.ethAddr)),
auth.Allow("TaskStatus", "StopTask").With(newDealAuthorization(ctx, h, &fieldIdMetaData{hub: h})),
auth.Allow("StartTask").With(newDealAuthorization(ctx, h, &fieldDealMetaData{})), …
```
=> refactor: auth configuration

insonmnia/locator/config.go, insonmnia/locator/server.go, insonmnia/locator/server_test.go, insonmnia/miner/util.go, locator.yaml, util/util.go
Locator can now work in `only_public_ips` mode.
* If hub announces its IPs and none of them is public, an error is returned.
* If some of the announced IPs are public, announcement is successful (only public IPs are written to db, skipped IPs are logged).
* Config field `only_public_ips` is optional.
=> feat: only_public_ips mode for locator

insonmnia/locator/server.go, insonmnia/locator/server_test.go
A bug was introduced in an earlier commit that allowed hubs to announce endpoints without ports while in `only_public_ips` mode; this commit fixes the problem.
=> fix: locator rejects announcements without ports

insonmnia/miner/server.go
This PR just close overseer at Worker's finishing. It required for correct GPU plugin unloading and socket closing when Nvidia-embedded is used;
=> fix: close overseer

insonmnia/node/tasks.go
This PR fix deals retrieving for the `tasks list` command.
The deals used to obtain the Hub address, then resolving IP address via the Locator and then load tasks list via the gRPC.
the Node needs only accepted deals in that context because only with the accepted deal the Hub can start client's tasks.
the `tasks list` call now takes up to 2/3 less time from the previous implementation.
=> fix: decrease orders loading time

insonmnia/miner/server.go
This PR defers an overseer creation to the end of Worker's init.
In that case, we don't need to call `cancel()` and `ovs.Close()` every time we met an error.
=> fix: create ovs and cancel func as late as possible

insonmnia/miner/overseer.go
In general we also need a cleanup gc routine, but for now we just need to leave containers to provide access to logs and so on.
=> fix: do not remove container after commit

insonmnia/hub/cluster.go
Fixes segfault in cluster that happens if `failover` is `true` and `boltdb` is used.
=> fix: segmentation fault in cluster

insonmnia/miner/config_test.go, insonmnia/miner/gpu/interface.go, insonmnia/miner/gpu/nvidia_tuner.go, insonmnia/miner/gpu/options.go, insonmnia/miner/gpu/radeon_tuner.go
Chained with #438
GPU tuners now use Docker volumes instead of binds to provide GPU-related stuff
=> refactor: gpu tuner volumes

insonmnia/miner/config_test.go, insonmnia/miner/gpu/nvidia_tuner.go, insonmnia/miner/gpu/radeon_tuner.go
Chained with #438, #439 
Now GPU tuners can check if required hardware is present on the Worker's machine.
=> feature: GPU tuner hw detect

insonmnia/miner/gpu/interface.go, insonmnia/miner/gpu/nvidia_tuner.go, insonmnia/miner/gpu/radeon_tuner.go, insonmnia/miner/gpu/tuner_other.go
This PR remove lots of GPU-related libraries collected on host, leaves an only minimal amount of libs required to set-up tasks executed on the graphics card.
NVidia:
- `libnvidia-ml.so` is required;
- leaving `nvidia-smi` as useful diagnostic tool;
Radeon:
- collecting libs on the host is not required at all, only the `/dev/dri` and `/dev/kfd` is required to be mounted into the container;
=> refactor: minify amount of libs used for GPU Tuners

insonmnia/hub/cluster.go, insonmnia/hub/server.go
* Only leader's client endpoints are announced;
* Non-leaders reject client requests.
=> feat: only leader serves clients

insonmnia/hub/cluster.go, insonmnia/hub/server.go
With `failover` disabled, hub failed to announce client endpoints because `leaderID` was not set. This PR sets `leaderID` to current node ID when `failover` is disabled.
=> fix: set leaderID to self if failover is disabled

insonmnia/hub/cluster.go, insonmnia/hub/server.go
For some reason (possibly a broken merge) `runCluster()` is called twice.
=> fix: duplicate runCluster

insonmnia/miner/gpu/options.go
changed:
- Mount GPU-related libs into the `/usr/local/nvidia` to prevent compatibility breaks.
=> fix: revert the GPU library mount path

Makefile, debian/changelog
* Break: massive protocol breakage.
All components with the same version are guaranteed to work, while otherwise - are not.
* Added: distributed tracing and audit.
This quite large addition includes utilities for ease debugging and finding out what the hell
is going on: audit logs and distributed tracing.
Now all server components are constructed with audit logs interceptor, which writes a record
when an RPC request finishes. It includes: time spent, tracing info (new feature), peer
wallet etc.
* Added: improved the gateway by allowing several reals under the same virtual service (#363).
Each internal Docker port can now be exposed into several external to avoid ambiguity in the
case of complex containers which run more than one network service.
* Added: auto-completion for the sonmcli …
=> version: bump - 0.3.1

insonmnia/hardware/gpu/cl.go
changed:
- Checked that `getPlatforms` return code -1001, handling it as non-error case and return empty GPUs for the machine;
- Note: constant is hardcoded because of error -1001 returns from the plugins, [not OpenCL itself](https://streamhpc.com/blog/2013-04-28/opencl-error-codes/).
=> fix: properly handle PLATFORM_NOT_FOUND error from OpenCL

insonmnia/hub/server.go
=> fix: close expired deals

cmd/hub/main.go, cmd/locator/main.go, cmd/miner/main.go
changed:
- Init a logger as early as possible;
- If there is no logger context yet, using simple cmd.Printf for user-friendly error messages
=> refactor: pretty error messages on components startup

cmd/cli/commands/printers.go, proto/bigint.go, proto/bigint_test.go
added:
- Bigint.ToPriceString() method to convent Wei-ordered to Ether-ordered values
changed:
- update deal info printer, now it shows price per second and deal duration
=> fix: show price as SNM-ordered value, not as Wei-ordered

insonmnia/miner/gpu/nvidia_tuner.go
libcuda.so is coming from NVidia drivers, not with CUDA runtime installer,
so we need to add it to the container
=> fix: add libcuda to the NVidia drivers volume

cmd/cli/commands/printers.go, cmd/cli/commands/printers_test.go, proto/bigint.go, proto/timestamp.go
changed:
- check deal duration before price calculation
- typecast proto's Timestamp to time.Time with UTC, not local timezone
=> fix: zero division if deal duration is zero

Makefile, cmd/hub/main.go, cmd/locator/main.go, cmd/miner/main.go, cmd/node/main.go, hub.yaml, insonmnia/hub/config.go, insonmnia/hub/config_test.go, insonmnia/logging/logging.go, insonmnia/logging/logging_test.go, insonmnia/miner/cgroup_test.go, insonmnia/miner/config.go, insonmnia/miner/config_test.go, insonmnia/node/config.go, node.yaml, vendor/github.com/jinzhu/configor/README.md, vendor/github.com/jinzhu/configor/configor.go, vendor/github.com/jinzhu/configor/utils.go, vendor/vendor.json, worker.yaml
changed:
- Service configs now receive logging level as a string, not a numeric value. Fallback level is "debug".
- Config interface returns zapcore.Level to build logger instance from configured values.
- `debug` parameter is removed from BuildLogger, logger always in "production" mode with the eye-candy "console" encoding. Because nobody changes this mode during half a year `¯\(ツ)/¯`
=> feat: represent logging level as string

insonmnia/hub/acl.go, insonmnia/hub/acl_test.go, insonmnia/hub/server.go
added:
- `multiAuth` implementation of an `auth.Authorization` that allows to combine and apply different auth types.
changed:
- `Hub.TaskStatus` method wrapped with both `TransportAuthorization` and `DealAuthorization`.
=> fix: check for supplier and buyer auth on TaskStatus

insonmnia/node/market.go, proto/rendezvous.pb.go
Also removes  accidentally committed `proto/hub.pb.go2`.
=> refactor: remove code duplication into Node's ExecOrderHandler

blockchain/api.go, cmd/cli/commands/common.go, cmd/cli/commands/tokens.go, insonmnia/hub/eth.go, insonmnia/hub/eth_test.go, insonmnia/hub/server_test.go, insonmnia/node/deals.go, insonmnia/node/market.go, insonmnia/node/market_test.go, insonmnia/node/tasks.go
We need to perform a correct cancellation and do not want to break a context when communicating with blockchain.
=> fix: pass context to the ethereum interface

insonmnia/npp/listener.go, insonmnia/npp/options.go, insonmnia/npp/puncher.go
Changed:
- Now NPP listener allows to connect to the rendezvous asynchronously with the default TCP listening. This fixes a bug where Hub server was broken in the case of serving incoming connections.
- NPP has now exponentially backoff timeout to avoids log spamming.
Dev:
- ConnTuple now hides an error, because Zap checks for error interface explicitly.
=> feat: parallel NPP and TCP listening

cmd/cli/commands/client.go, cmd/cli/commands/common.go, cmd/node/main.go, etc/node.yaml, insonmnia/node/config.go, insonmnia/node/server.go, util/xgrpc/client.go
Changed:
- Node binds to IP socket.
- Node's config accepts only port number, binds always to localhost (ipv6 and ipv4).
- CLI connects to Node via unencrypted gRPC connection.
Removed:
- `NewUnencryptedUnixSocketClient` because it becomes completely useless.
=> refactor: bind node to ip socket instead of unix socket

insonmnia/gateway/router.go, insonmnia/gateway/router_linux.go, insonmnia/gateway/router_nonlinux.go
I'm accidentally found this issue when running `go vet ./...`.
=> refactor: adopt extracted router, fix cycle import issues.

.mailmap
Used for tools like `git shortlog -se` to work properly.
=> chore: mailmap

insonmnia/rendezvous/resolve.go
Fixed:
- No longer eat an error returned while reading body.
- Trim whitespaces in the body response.
=> fix: check errors, trim whitespaces

insonmnia/npp/net.go
While resolving private IP addresses for publishing them on Rendezvous it's normal to immediately return local address if it is not unspecified.
Otherwise self-resolution should occur.
=> fix: proper IP filtering

etc/worker.yaml, insonmnia/benchmarks/benchmarks.go, insonmnia/hub/server_test.go, insonmnia/miner/cgroup_test.go, insonmnia/miner/config.go, insonmnia/miner/config_test.go, insonmnia/miner/server.go, insonmnia/miner/server_test.go
Added:
- Able to configure URL for list loading.
- `BenchList` now have an implementation that loads it from external storage.
Changed:
- Container result's JSON now identified by the `code` field, not an ID (go cannot use numbers as map keys for JSON).
=> feat: load benchmarks list externally

insonmnia/cgroups/cgroup.go, insonmnia/cgroups/cgroup_linux.go, insonmnia/cgroups/cgroup_nonlinux.go, insonmnia/hardware/hardware.go, insonmnia/hardware/marshal.go, insonmnia/hardware/mem/device.go, insonmnia/hub/server.go, insonmnia/miner/options.go, insonmnia/miner/server.go, insonmnia/resource/pool.go
Previously we used total amount RAM on the host system as an available memory for scheduling.
But resources for containers may be limited by a parent CGroup settings.
This PR changes how available memory amount is measured.
The lesser value of `total RAM on host, a limit set for CGroup`
is used.
Changed:
- CGroups management code moved into a separated package to prevent cycle imports issue.
- `insonmnia/hardware/mem` package was updated to unify the hardware descriptions.
- CGroup interface extended with `Stats` method, used to get an internal cgroup stats for various resources.
=> feat: read memory limit from CGroup

etc/worker.yaml, insonmnia/benchmarks/benchmarks.go
Changed:
- Downloading of the benchmarks list can be skipped for development purposes.
- List now can be loaded from the filesystem, the `file://` schema support added.
=> fix: tune benchmark list loading

cmd/relay/main.go, cmd/rv/main.go, insonmnia/auth/addr.go, insonmnia/hub/server.go, insonmnia/node/hub.go, insonmnia/npp/config.go, insonmnia/npp/options.go, insonmnia/npp/relay/config.go, insonmnia/npp/relay/server.go, insonmnia/rendezvous/config.go, insonmnia/rendezvous/server.go, util/netutil/net.go
Changed:
- Use self-unpackable structs as a building blocks for configurations. This includes `TCPAddr` and `auth.Addr`.
Removed:
- No longer used convertions.
=> refactor: npp config overhaul

insonmnia/npp/listener.go
Since we're relying on three asynchronous channels while waiting for incoming connection, this action can be performed without timeout as usual `accept` does.
=> fix: drop unused timeout

cmd/hub/main.go, cmd/relay/main.go, cmd/rv/main.go, etc/worker.yaml, insonmnia/hub/config.go, insonmnia/hub/config_test.go, insonmnia/hub/server.go, insonmnia/hub/server_test.go, insonmnia/logging/logging.go, insonmnia/logging/logging_test.go, insonmnia/miner/config.go, insonmnia/miner/config_test.go, insonmnia/node/config.go, insonmnia/npp/relay/config.go, insonmnia/npp/rendezvous/config.go
Added:
- Explicit log level configuration struct that can be used as a building block for constructing configurations. It is parsable from YAML and throws errors at the parsing stage, avoiding doing additional checks.
Changed:
- Constructing a new Hub no longer requires a context parameter, because it was anyway ignored.
- Remove logging section from worker config. Hub's and Worker configs should be merged in the nearest future.
=> refactor: logging configuration

insonmnia/hub/server.go, insonmnia/node/server.go, insonmnia/npp/relay/monitor.go, insonmnia/npp/rendezvous/server.go, util/xgrpc/options.go
This commit activates gRPC request/response auto-validation by injecting an interceptor.
Those requests/responses that require validation can optionally implement an implicit `Validate() error` function that will be called before request starts being processed and before response passed to the gRPC internals.
=> feat: auto request/response validation

insonmnia/logging/config.go, insonmnia/miner/config.go, insonmnia/npp/relay/config.go, insonmnia/npp/rendezvous/config.go
While developing an auto-sell bot, I've discovered that we reinvent a LoggingConfig each time we write a new component.
Let's finish this.
=> refactor: logging config decomposition

cmd/relay/main.go, cmd/rv/main.go, cmd/worker/main.go, insonmnia/logging/config.go, insonmnia/logging/logging.go, insonmnia/node/config.go
Suddenly configor parses the config into each struct twice: once for loading from file, and once while processing tags.
If a field has default value (all types in go has default value, and this is terrible) equaled with the same value specified in the config, and at the same - has required attribute - configor blows up.
To avoid this I specified logging level as a pointer. Now levels should load nicely, but still all this looks weird.
=> fix: workaround configor weird logging parsing

insonmnia/hub/options.go, insonmnia/hub/server.go, insonmnia/hub/server_test.go
This PR removes useless blockchain, marketplace and
state storage clients from the Hub and their options.
=> chore: drop unused options from Hub

proto/insonmnia.go
This caused SIGSEGV during processing `sonmcli worker ask-plan list` request.
=> fix: nil safe YAML marshaller for ETH address

insonmnia/miner/network/tinc_ipam.go
ARM has 32 bit int by default
```➜  core git:(master) ✗ GOARCH=arm GOARM=7 make build
+ build/worker
CGO_LDFLAGS_ALLOW= CGO_LDFLAGS= CGO_CFLAGS= go build -tags "nocgo " -ldflags "-s -X main.appVersion=v0.3.3-0462b8f1" -o target/sonmworker_linux_x86_64 ./cmd/worker
insonmnia/miner/network/tinc_ipam.go:137:17: constant 4278190080 overflows int
Makefile:62: recipe for target 'build/worker' failed
make: *** [build/worker] Error 2
```
This fix is ugly a bit. But I do not want to reorder << and &.
=> arm: fix build for raspberry PI

proto/insonmnia.go, proto/insonmnia_test.go
This PR implements `MarshalText` and `UnmarshalText` methods for the `EthAddress` type.
It allows satisfying both JSON and YAML marshallers requirements.
=> refactor: proper marshalling for EthAddress

cmd/cli/commands/printers.go
As noticed in #686 ( [line](https://github.com/sonm-io/core/pull/686/files#diff-c6365e7cdd271a7c4c9cf1e39f85a62dR311) )
=> fix: correctly compare an empty timestamps

insonmnia/benchmarks/benchmarks.go, insonmnia/miner/server.go
Some of the mining software and other GPU-related stuff exists in two version:
CUDA- and OpenCL- based. We need to know what type of device is connected 
to the container, it allows us to start corresponding software to benchmark GPU properties.
=> chore: add vendor to container's ENV when GPU benchmark starting

util/rest/errors.go, util/rest/server.go
This should prevent to seeing errors like HTTP 500 when something not found.
=> fix: properly forward gRPC REST errors

insonmnia/miner/server.go
Now Worker waits until container is finished,
then reads and parses whole logs.
=> fix: proper logs reading for benchmarks

insonmnia/dwh/server.go, insonmnia/dwh/server_test.go
This PR fixes the timing of updating profile stats (active asks/bids): from "update when the deal is closed" to "update when the deal is opened".
=> fix: update profile stats (DWH)

cmd/cobra.go
Unfortunately merging #744 resulted in a new bug: currently it's impossible to print a version without specifying some configuration file path.
This PR should fix this.
=> fix: asking a version should no longer require config

etc/worker.yaml, insonmnia/dwh/config.go, insonmnia/matcher/matcher.go, insonmnia/miner/config.go, insonmnia/miner/server.go, insonmnia/node/config.go
Changed:
- Disableable matcher into a Worker.
- Extract DWH ClientConfing, reuse it into Worker and Node.
=> chore: unify configs

cmd/cli/commands/common.go, cmd/cli/commands/deals.go, cmd/cli/commands/orders.go, cmd/cli/commands/tasks.go, cmd/cli/commands/tokens.go
This PR changes CLI sub-commands semantic to follow the "entity-action"
commands style.
=> refactor: make cli commands more consistent

insonmnia/dwh/postgres.go, insonmnia/dwh/server.go, insonmnia/dwh/sql.go, insonmnia/dwh/sqlite.go, insonmnia/dwh/storage.go
* [Coordinated with UI team and analysts] DWH used to create blank profiles for orders with previously unknown authors; this PR removes this behavior;
* Profile stats updates are optimized;
* Uniqueness constraint for certificates `(OwnerID, ValidatorID, Attribute, Value)` is removed because analysts and blockchain guys insist that issuing identical certificates is O.K.
=> Feat: dwh sql updates

insonmnia/node/server.go, insonmnia/npp/options.go, insonmnia/npp/puncher.go, insonmnia/npp/rendezvous/config.go, insonmnia/worker/server.go
This PR allows to configure timeouts and the number of connection attempts for NAT punching.
Also reduced default timeout to 1s.
=> feat: configurable timeouts for NPP

insonmnia/npp/listener.go, insonmnia/npp/metrics.go, insonmnia/worker/server.go
This commit allows to fetch NPP metrics, where counting of the number of incoming connection occurs.
Also it provides Rendezvous connection status, which is used in `worker status` CLI.
=> feat: NPP metrics

etc/worker.yaml, insonmnia/worker/config.go, insonmnia/worker/server.go
This commit allows to specify admin ETH key for a worker to be able to have access to worker management tools.
=> feat: worker admin

etc/worker.yaml, insonmnia/worker/cgroup_test.go, insonmnia/worker/config.go, insonmnia/worker/config_test.go, insonmnia/worker/options.go, insonmnia/worker/server.go
subj
* master now is required
* generated keys are exported to sonm folder to ease usage
* useless keys config section is dropped from config
* Add ability to start in dev mode without master check
=> refactor: make master required, export generated keys

accounts/multi_keystore.go, cmd/cli/commands/common.go, cmd/cli/commands/login.go
This PR fixes CLI's behaviour in the following way:
- save password for newly generateg keys on `sonmcli login`.
- look for pre-saved key into config, ask interactively if no saved password provied.
=> fix: default account password

cmd/cli/commands/common.go, cmd/cli/commands/master.go, cmd/cli/commands/tasks.go, insonmnia/hardware/hardware.go, insonmnia/npp/net.go, insonmnia/worker/options.go, insonmnia/worker/server.go, insonmnia/worker/server_test.go, insonmnia/worker/util.go, proto/net.go, util/certs.go, util/netutil/net.go, util/netutil/net_test.go, util/util.go, util/util_test.go
Changed:
- Replace `util.PubKeyToAddr` with `crypto.PubkeyToAddress`.
- Drop `ParseEndpointPort`.
- Move all network-related stuff to netutil package.
=> refactor: make utils great again

Makefile
Move `node_modules` to installing node module before build.
=> chore: installing node modules first

blockchain/source/contracts/SNMD.sol
Fix typo `Develompent` => `Development`
=> chore: typo SNMD

insonmnia/dwh/config.go, insonmnia/dwh/server.go, insonmnia/dwh/sql.go, insonmnia/dwh/storage.go
This PR introduces correct parallel processing of blockchain events (the idea is to avoid any errors that are not related to DB/geth node availability).
Entities have a lifetime: `X Created`, `X Modified 1, 2, 3`, `X Deleted`. The algorithm splits events into groups by their type and executes events within a group in parallel. Event groups are ordered so that a situation when, say, `X Modified` event is processed after `X Deleted` is impossible.
Also there's a fix for duplicate Worker entries (was possible because `Market` doesn't check for duplicates).
=> feat: error-free concurrency for DWH

insonmnia/npp/puncher.go
For some unknown reasons I forgot to extract incoming connections in the Puncher.
This lead to a situation when one peer succeed to establish a connection, but nothing happened, because the other side accepted that connection and did nothing with it.
=> fix: puncher should extract incoming connections

blockchain/api.go, insonmnia/node/tokens.go
Now the tokens api uses common.Address instead of string.
It can safe us with same string-to-addres casting problem.
=> chore: simplify tokens api

insonmnia/worker/config.go, insonmnia/worker/server.go, util/debug/pprof.go
This commit activates debug subsystem in the worker by optionally running a debug HTTP pprof server.
=> feat: debug worker via pprof on demand

insonmnia/worker/server.go, proto/ask_plan.go
Now we use indexes from ask-plan to determine gpu hash instead of hardware. This allows to use GPU indexes as they appear in ask-plan rather then in hardaware
=> fix: use askplan hasher instead of hardware hasher 

Makefile, appveyor.yml
Now binaries produces by make contain the proper OS and ARCH suffixes even if they are compiled using cross-compilation feature.
Hence, there is no need for `build/*_linux` and `build/*_win32` targets. Now cross-platform binaries can be build using something like this:
`GOOS=windows GOARCH=386 make build/node`
You can read more about supported platforms and architectures: https://github.com/golang/go/wiki/MinimumRequirements.
=> refactor: makefile design

insonmnia/worker/network/tinc_network.go, insonmnia/worker/overseer.go, insonmnia/worker/salesman/salesman.go
This PR: 
* Fixes situation when worker did not get deal notification when ask-plan was scheduled for deletion.
* Restores cleanup call on container.
* Uses sigkill with no regret for tinc as it does not respond to ContainerStop anyway.
This all results in a proper cleanup of the deal containers and resources release.
=> fix: proper container cleanup on finished deal

accounts/keys.go, accounts/keys_test.go, accounts/multi_keystore.go, util/util.go
In some cases there could be underlying error while determine whether file(dir) exists or not. This PR changes return type to error, which is more descriptive and removes f.IsDir() call on the nil receiver.
=> fix: possible segfault in FileExists and DirectoryExists

insonmnia/node/server.go, insonmnia/npp/dial.go, insonmnia/npp/listener.go, insonmnia/npp/options.go, insonmnia/npp/puncher.go, insonmnia/npp/relay/client.go, insonmnia/npp/relay/frame.go, insonmnia/worker/server.go
Changed:
- More logs while connecting using NPP.
- Log details in the Puncher.
- Log addresses and protobuf messages as JSON instead of <"\unreadable strings\">.
- Filter duplicate error messages, while attempting to punch a NAT.
- Some typos fixed.
Fixed:
- Possible infinite hanging while punching multiple private addresses.
=> refactor: attempt to log everything in NPP

optimus/optimus.go
For some strange reason we use internally duration representation of nanoseconds. At the other side market API uses seconds as a quantum.
This fix converts market representation to worker's one.
=> fix: convert duration to nanoseconds

insonmnia/dwh/sql.go
* target order's `CounterpartyID` filter takes candidate orders' MasterID into account;
* candidate orders' `CounterpartyID` filter takes target orders' MasterID into account;
* `Duration` filter is simplified (redundant branch is removed);
* Blacklist filter that was broken for Postgres is fixed.
=> fix: GetMatchingOrders Blacklists and CounterpartyID (DWH)

blockchain/source/contracts/Market.sol, blockchain/source/test/market.js
Now we can place Order with any count of benchmarks (but still not more than we support).
In Deal now always stored the correct num of bencmarks (num that sonm supported when deal was opened)
=> feat: reworked benchmarks in market

blockchain/source/contracts/Market.sol, blockchain/source/migrations/7_deploy_market.js, blockchain/source/test/blacklist.js, blockchain/source/test/market.js
- Now netflags stores in dynamic array.
- We can update num of netflags without both breaking API and redeploy market.
- CreateOrder accepts any count of netflags (less or eq we support).
- New event NumNetflagsUpdated.
-  New param in market constructor.
=> feat: store netflags in dynamic array on market

optimus/devices.go, optimus/devices_test.go
This commit applies previous changes to every other data consumer in the autosell bot, so it prevents losing precision while conversing from uint64 -> float -> uint64 while doing math.
=> fix: ceil everything in Optimus

blockchain/addresses.go, blockchain/api.go, blockchain/options.go, blockchain/util.go
This PR adds several files after the #976:
- `gasLimit` param added to chainOpts.
- Replaced constant usage with chainOpts param.
- Constants with defualt gas limit and gatekeeper addresses renamed using Sidechain\Masterchain.
=> fix: move gasLimit into chainopts

accounts/multi_keystore.go, accounts/multi_keystore_test.go, cmd/cli/commands/login.go
This PR fixes two bugs:
- Now we do not mark the key as default if there is only one key is present into keystore.
- Now `sonmcli login` asking for pass-phrase, then trying to decrypt key and mark it as default only if decryption was successful.
=> fix: proper cli login behaviour

blockchain/addresses.go, blockchain/api.go, blockchain/config.go, blockchain/examples/placeOrder/placeOrder.go, insonmnia/node/tokens.go
Try to use master/side-chain terminology everywhere.
=> chore: blockchain api naming

cmd/cli/commands/tasks.go, insonmnia/worker/docker.go, insonmnia/worker/overseer.go, insonmnia/worker/server.go
subj uses ImageLoad instead of import, which respects multiple layers as the opposite command save produces
=> fix: proper task push

insonmnia/npp/dial.go, insonmnia/npp/options.go
This should remove weird warnings like: `failed to construct a puncher	{"error": "failed to connect to []"}` when no rendezvous endpoints specified in the config.
=> fix: do not spam warnings when no rendezvous specified

optimus/optimus.go
Now Optimus should log benchmarks as an array, not protobuf.
=> chore: better logs

optimus/learning_test.go, optimus/math.go
Autosell bot should no longer fall into millions of NaNs after calculating relative order weights.
=> fix: proper sigmoid implementation

optimus/learning.go
When DWH was young it was unable to return properly created timestamp, we inited it ourselves.
Now times change, but those empty initialization was forgotten and cause strange autosell bot behaviour.
This commit removes such initialization.
=> fix: do not null order created timestamp

insonmnia/npp/relay/server.go
In case of being run on IPv6 it improperly answers to a discover request with address not surrounded with braces.
Now this part is okay.
=> fix: make relay IPv6 ready (not really)

accounts/identity.go, accounts/multi_keystore.go, blockchain/api.go, blockchain/util.go, insonmnia/dwh/config.go, insonmnia/dwh/server.go, insonmnia/dwh/server_test.go, insonmnia/dwh/sql.go, insonmnia/dwh/storage.go, insonmnia/matcher/matcher.go, insonmnia/node/blacklist.go, insonmnia/node/deals.go, insonmnia/node/market.go, insonmnia/node/tasks.go, insonmnia/node/tokens.go, insonmnia/structs/network_spec.go, insonmnia/worker/container.go, insonmnia/worker/network/l2tp_config.go, insonmnia/worker/network/l2tp_ipam.go, insonmnia/worker/network/l2tp_network.go, insonmnia/worker/network/l2tp_state.go, insonmnia/worker/network/tinc_driver.go, insonmnia/worker/network/tinc_network.go, insonmnia/worker/network/tinc_state.go, insonmnia/worker/options.go, insonmnia/worker/salesman/salesman.go, insonmnia/worker/server.go, insonmnia/worker/whitelist.go, optimus/normalize.go, proto/rendezvous.go
This PR removes usage of `errors.Wrap` and `errors.WithMessage`, format all errors using `fmt.Errorf` and replaces imports with "errors" package. 
Some mistypes in error messages are accidentally fixed, also lowercased err message text to be consistent with the Golang standards.
=> chore: drop pkg/errors, wrap errors using fmt.Errorf

insonmnia/node/server.go, insonmnia/npp/dial.go, insonmnia/npp/listener.go, insonmnia/npp/options.go, insonmnia/npp/relay/client.go, insonmnia/npp/relay/config.go, insonmnia/worker/config_test.go, insonmnia/worker/server.go, util/netutil/net.go
This change allows to utilize specifying hostnames as a relay address, increasing stability.
Previously such hostname was resolved once at construction time and the relay client tried to connect to the resolved TCP addresses even if some of them are already down.
Now each time a client requires new connection hostname resolution occurs. All this allows dynamic addition/removal backends under the DNS.
Of course we try to connect to all returned endpoints.
=> feat: utilize hostname for Relay

blockchain/api.go, insonmnia/worker/server.go, insonmnia/worker/whitelist.go, insonmnia/worker/whitelist_test.go
This PR takes consumer identity level in concern. If customer has at least IDENTIFIED level whitelist checking doesn't take place
=> refactor: do not apply whitelist to identified consumers

etc/optimus.yaml, insonmnia/auth/addr.go, optimus/config.go, optimus/optimus.go
Now it is possible to define some worker specific settings in the autosell bot config.
For example now we can specify epoch interval, where the bot scans worker's resources and tries to sell them.
This is a BREAKING change.
=> feat: specify worker settings in Optimus config

optimus/optimus.go
Previously the autosell bot could match more than a single order with incoming network required. Because we do not allow such behaviour it led to multiple errors while trying to create sell plans.
This change explicitly disables incoming network after a first matching orders found.
=> fix: optimus should now track incoming network

optimus/config.go, optimus/learning.go, optimus/learning_test.go, optimus/math.go, optimus/model.go, optimus/optimus.go
Changed:
- Model and classifier factories now has appropriate names.
- Decomposed model and classifier creation logic into their sub-functions instead of doing this directly in unmarshallers.
- Forward logger to models.
- Some comments added.
=> refactor: prepare optimus cancelling orders

blockchain/api.go
Transacting with ethereum is racy and there may
be conditions when we send transactions with wrong
nonces, etc. The safest way to handle such conditions
is trying to re-send our transactions a couple of
times.
=> feature: add a wrapper to abigen api calls to retry

optimus/optimus.go
Now Optimus will check for netflags inclusion using free devices instead of just devices.
=> fix: invalid netflag filtering

cmd/cli/task_config/config_test.go, insonmnia/worker/server.go
This fixes forgetting "expose" section while forwarding it from start task request to a container.
Also a tiny test added to check whether the task config is parsed properly.
=> fix: properly forward "expose" section in Worker

optimus/devices.go, optimus/devices_test.go
This fixes a bug where Optimus fails to fit GPU benchmarks with some of them equal zero.
=> fix: properly handle zero GPU benchmark

cmd/cli/commands/tokens.go
This commit increases timeout for `sonmcli token deposit`
method. The average time of command execution is about 100s with
a default timeout of 60s. So for a user it looks like that command
is always failing.
This PR absorbs #1111.
=> fix: increase timeout for deposits command

etc/optimus.yaml, optimus/config.go, optimus/optimus.go
This allows to specify worker's total price threshold in the Optimus config.
If the new set will gain more profit/hour than the specified value some of ask plans will be replaced.
=> feat: specify worker price threshold in Optimus

optimus/devices.go, optimus/devices_test.go
When combining orders into a device manager, sometimes, when further benchmarks did not fit in the set, Optimus stole those resources, making all following attempts to fail with resource exhausted error.
This commit fixes that behaviour.
Also as a minor optimization fast GPU filtering by memory was introduced.
=> fix: transaction like consumption in Optimus

task.yaml
This commit updates task.yaml with actual sha256 of httpd container
that in the allowed list now.
=> chore: update task.yaml example

insonmnia/worker/overseer.go
This PR fixes behaviour when deal was finished, but task resources were not released as status event was not delivered via status channel
=> fix: proper value in status channel

cmd/cli/commands/blacklist.go, cmd/cli/commands/common.go, cmd/cli/commands/deals.go, cmd/cli/commands/err_test.go, cmd/cli/commands/login.go, cmd/cli/commands/master.go, cmd/cli/commands/orders.go, cmd/cli/commands/printers.go, cmd/cli/commands/profiles.go, cmd/cli/commands/tasks.go, cmd/cli/commands/tokens.go, cmd/cli/commands/version.go, cmd/cli/commands/worker.go, cmd/cli/commands/worker_askplans.go, cmd/cli/commands/worker_benchmarks.go, cmd/cli/commands/worker_devices.go, cmd/cli/commands/worker_tasks.go, cmd/cli/main.go
This commit changes CLI behavior in the following way:
1. Using RunE instead of Run for each cobra command.
2. Setting SilenceUsage = true, if not - cli will print help usage on every error.
3. Setting SilenceErrors = true, if not - cli will show their own error and then handle out custom code that controls the os.Exit status.
4. Introducing `newCmd` and `newCmdWithKeys` wrappers. The first one is used to wrapping cobra.Command with `SilenceUsage` and  `SilenceErrors` flags. The second one is used to wrapping command with the key loading code (if required and not handled externally).
5. Removed all of `os.Exit(1)` calls, excepts only one that handles single point of error handling now.
=> proposal: better error handling for the cli

cmd/cli/commands/common.go, cmd/cli/commands/err_test.go, cmd/cli/commands/printers_test.go, cmd/cli/commands/version_test.go, cmd/cli/config/config.go, cmd/cli/main.go
Might be useful for debugging when we have two or more nodes on one host, so we don't have to re-login all the time, can specify node addreses in config etc.
=> feat: let cli read it's config from --config flag

util/netutil/net.go
In case of IPv6 addresses it properly wraps the given address with [] braces.
=> fix: properly join host with port

insonmnia/node/deals.go
This commit adds checking that current user's key is a consumer key,
if so - the node will try to connect to the related worker using NPP,
otherwise - skip connection.
=> fix: avoid extra request for worker if user is not consumer

optimus/blacklist.go, optimus/engine.go, optimus/optimus.go
This change activetes blacklists support in Optimus. Now orders whose author is in worker's blacklist are now filtered out. The same thing happens at the opposite: when worker's address is in the order's blacklist.
=> feat: blacklist support in Optimus

insonmnia/npp/relay/errors.go, insonmnia/npp/relay/hashring.go, insonmnia/npp/relay/hashring_test.go, insonmnia/npp/relay/server.go
This fixes a bug in the Relay server, when it suddenly devastates the continuum, returning 0.0.0.0 on any discovery request.
Also it fixes a bug introduced in #1046, when an inproperly configured node stopped to work.
=> fix: spurious continuum devastation

optimus/engine.go
Otherwise they will have 0 weigth and will be replaced at every opportunity.
=> fix: assign created timestamp for worker's own orders

insonmnia/node/server.go, insonmnia/npp/dial.go, insonmnia/npp/listener.go, insonmnia/npp/options.go
Suddenly we discovered that there is no need for passing context
variables into NPP dialer and listener's construction functions.
=> refactor: properly use context in NPP

cmd/dwh/main.go, cmd/node/main.go, cmd/worker/main.go, util/metrics/prometheus.go, util/util.go
This commit allows metrics server (backed with Prometheus) to be run either in secure or insecure modes.
After minor decomposition it is also possible to wire provided context with server's lifetime, which fixes at last some of leaked goroutines.
Now all metrics-related stuff lives in "metrics" namespace. Util must die.
=> refactor: metrics server overhaul

.travis.yml, Makefile, etc/dwh.yaml, insonmnia/dwh/config.go, insonmnia/dwh/server.go, insonmnia/dwh/server_test.go, insonmnia/dwh/sql.go, insonmnia/dwh/storage.go
This PR removes `sqlite3` support from DWH.
Postgres for tests runs in a docker container.
A new target (`make test/lite`) is added to `Makefile`, it runs tests **without** DWH tests. Old target `make test` sets up a docker container with `postgres` and runs **all** tests (including DWH).
=> chore: drop sqlite3 (DWH)

insonmnia/resource/pool.go, insonmnia/worker/overseer.go, insonmnia/worker/server.go
When the container dies, or the task is stopped we keep all the task's data until the deal is finished, but we don't keep the task-to-askplan data deleting in ReleaseTask method. So when we ask for logs or any other data on an already stopped container, we will end up in the following error:
```
./sonmcli_darwin_x86_64 tasks logs 157 521845a3-ad69-49a5-b717-2cc0dd7fec5a
[ERR] Cannot fetch log chunk: rpc error: code = Unknown desc = failure during receiving logs from worker: rpc error: code = NotFound desc = ask plan for task 521845a3-ad69-49a5-b717-2cc0dd7fec5a not found: ask plan for task 521845a3-ad69-49a5-b717-2cc0dd7fec5a is not found
```
This patch proposes keeping this info until the deal is closed, so we can, for instance, still ask for logs on a stopped container:
```
$ …
```
=> fix: Keep task-to-askplan data till the deal is finished

etc/dwh.yaml, insonmnia/dwh/server.go
prettify locks for `serveGRPC()` and `serveHttp()`.
notice: locking these sections is required to properly handle interrupts while startup.
=> chore: dwh startup refactoring

etc/optimus.yaml, optimus/config.go, optimus/engine.go, optimus/market.go, optimus/optimus.go
This commit allows to specify the minimum order price filter before fetching active orders from the marketplace. This is required to be able to ignore meaningless orders, that can possibly trick into submission regression model.
Also weight threshold was added to ignore orders that are too far from the predicted price, i.e. has price too much lower than the predicted one.
As a result, Optimus should no longer create ask plans with zero or almost-zero price.
=> fix: ignore orders with zero price in Optimus

insonmnia/dwh/sql.go
Adding duplicate entries to blacklist resulted in an error and a costly retry cycle. This PR makes DWH ignore such duplicates.
=> fix: ignore conflicts on AddedToBlacklist events (DWH)

insonmnia/oracle/config.go
Make `deviation percernt` level 1.0 default, not required.
=> fix: oracle config

insonmnia/node/master.go, insonmnia/node/server.go, insonmnia/node/tasks.go, insonmnia/node/worker.go, insonmnia/worker/server.go, util/xgrpc/method.go, util/xgrpc/options.go
This commit activates automatic request logging for gRPC services. This includes logging service and request names with tracing attributes if activated. Both unary and streaming API are supported.
Internally this is done by using gRPC request interceptors, that are invoked before the actual method called.
=> feat: pre-request logging interceptor

blockchain/config.go, blockchain/options.go, cmd/pandora/gun_marketplace.go, etc/node.yaml
This option now usefull for `deposit` and gatekeeper `withdraw`;
If option not defined gas price is determined by the latest blocks median gas price.
=> feat: make masterchain gas price configurable

etc/optimus.yaml
The new value is equivalent of ~0.48$ per day or 175.2$ per year.
=> chore: reduce default price threshold in Optimus

optimus/engine_branch.go
This adds a new model - Branch Bound Tree, which finds a global optimum solution for knapsack problem.
However, its complexity is still exponential, so it must be activated only when the number of matching orders is relatively low.
=> feat: branch bound model

cmd/optimus/main.go, etc/optimus.yaml, optimus/config.go, optimus/engine.go, optimus/engine_branch.go, optimus/engine_genetic.go, optimus/engine_greedy.go, optimus/engine_multi.go, optimus/learning.go, optimus/learning_test.go, optimus/model.go, optimus/model_lls.go, optimus/model_nnls.go, optimus/optimus.go
This commit allows to init each optimization model directly from the config.
Removed:
- Dropped "optimization.interval" option.
=> refactor: init everything from config in Optimus

insonmnia/worker/container.go, insonmnia/worker/network/l2tp_tuner.go, insonmnia/worker/network/tinc_tuner.go, insonmnia/worker/network/tuner.go, insonmnia/worker/overseer.go, insonmnia/worker/overseer_test.go, insonmnia/worker/plugin/plugin.go, insonmnia/worker/server.go
Curretnly a WIP, not everythin tested yet and the code's not that good. Things working so far:
A worker can attach on start to a running container, we can get it's stats etc. from the ```sonmcli```, stop the container, etc.
=> fix: handle tasks correctly in case of worker reload

insonmnia/npp/options.go, insonmnia/npp/puncher.go
This fixes using background "default" logger obtained from the Context. Instead preconfigured logger from options is used.
=> fix: avoid global logger in puncher

insonmnia/benchmarks/benchmarks.go, insonmnia/benchmarks/mapping.go
Added smart benchmark mapping alrorithm, which indexes benchmarks in a flat map backed with array.
This increases performance of genetic algorithm in 2-4 times.
Before (optimized 450 orders in 4m49.033336829s):
After: (optimized 452 orders in 1m20.653263813s):
=> perf: fast benchmark mapping

optimus/devices.go
It doesn't make sense to building combinations of GPUs with k more than n, which is the length of currently free GPUs.
=> perf: use proper combinations limits

Makefile, cmd/connor/main.go, connor/antifraud/antifraud.go, connor/antifraud/blacklist_watcher.go, connor/antifraud/config.go, connor/antifraud/log_processor.go, connor/antifraud/pool_processor.go, connor/antifraud/pool_processor_test.go, connor/config.go, connor/engine.go, connor/price/price.go, connor/price/price_test.go, connor/price/utils.go, connor/server.go, connor/types.go, connor/types_test.go, connor/x_test.go, debian/control, debian/rules, debian/sonm-connor.default, debian/sonm-connor.install, debian/sonm-connor.service, etc/connor.yaml
This commit introduces Connor, the bot which buying resources
for mining. The current implementation can:
- Places BID orders according to config.
- Restores orders, deals, and tasks between restarts.
- Loads actual price of the target token, create orders according to price and marginality coefficient.
- Tracks token price changes using CoinMarketCap, re-create orders if the price changed sufficiently.
- Looks for actual hashrate by logs and mining pool statistics.
- Closes deals which give us less hash-rate than offered.
Note that current implementation is strongly coupled with the Ethereum mining on the DwarfPool.
Next, we'll make it more modular and configurable for other popular tokens and pools.
=> feat: Connor the bot

etc/worker.yaml, insonmnia/worker/overseer.go, insonmnia/worker/plugin/plugin.go, insonmnia/worker/volume/btfs.go, insonmnia/worker/volume/cifs.go, insonmnia/worker/volume/driver.go, insonmnia/worker/volume/options.go, insonmnia/worker/volume/serve.go, task.yaml, util/xdocker/xdocker.go, util/xdocker/xdocker_test.go
This commit activates an ability to spawn SONM tasks with torrent
filesystem attached as a volume.
Internally this is achieved by using BTFS application that constructs a
torrent client and mounts itself on a filesystem via fuse. It's the
read-only solution designed to distribute large amount of data across
multiple task without single point of failure - all tasks help each
other to share the data, which reduces network pressure and improves
application scalability.
The contents of the files will be downloaded on-demand as they are read 
by applications. Tools like ls, cat and cp works as expected.
[![asciicast](https://asciinema.org/a/5ZIETLiht4r5SHRxZ19EnQV8n.png)](https://asciinema.org/a/5ZIETLiht4r5SHRxZ19EnQV8n)
=> feat: BTFS volume plugin for Worker

cmd/cli/commands/blacklist.go, cmd/cli/commands/common.go, cmd/cli/commands/deals.go, cmd/cli/commands/master.go, cmd/cli/commands/orders.go, cmd/cli/commands/profiles.go, cmd/cli/commands/tasks.go, cmd/cli/commands/tokens.go, cmd/cli/commands/worker.go
This commit fixes a problem when `--insecure` flag is used
with the CLI and some sub-command wants to load a key or
obtain a default eth address from the key store.
Therefore, now we'll load keystore prematurely for any command.
Now if insecure mode is activated, only TLS credentials creation
will be skipped for gRPC's client connection.
=> fix: load keystore even if `--insecure` flag is set

insonmnia/dwh/l1_processor_test.go, insonmnia/dwh/server_test.go, insonmnia/dwh/setup_test.go
Panics in DWH tests prevented teardown code from executing. This PR fixes the issue.
=> fix: ensure tests teardown after panics (DWH)

cmd/cli/task_config/config_test.go, cmd/cli/task_config/load_order.go
This commit fixes a bug when a user can accidentally create BID or ASK with fields that are unknown to the Node/Worker. Such behaviour is a source of confusion and frustration, so we just forbid unknown fields when doing "sonmcli order create" and "sonmcli worker ask-plan create".
=> fix: parse BID and ASK strictly

optimus/engine.go
This commit fixes a bug where during the calculation of free devices a mutation of meant-to-be-immutable field occurs, which lead to improper free devices state.
As a side effect one could see that Optimus performed invalid optimization in case where the most optimal ask-plans are already exist.
=> fix: properly calculate free devices in Optimus

connor/engine.go, connor/server.go, connor/types.go, connor/types_test.go, connor/x_test.go
This commit replaces corder's constrictor and some internals
that uses weird switch-case logic to control token-related parameters.
Fabric is constructed once when Connor is initializing and keeps
pre-defined params to create new instances if requred.
=> refactor: orders factory for connor

connor/config.go, connor/engine.go, connor/price/price.go, connor/server.go, connor/types.go, connor/types_test.go, connor/x_test.go
This commit aggregates token related params into the config.
The main idea is to keep all mining, pool and price watching interfaces
in the single point of configuration. It will give as an ability to configure
almost everything into a one place, thus adding new tokens can be performed
quickly and clearly.
=> refactor: token parameters for Connors

connor/antifraud/antifraud.go, connor/antifraud/blacklist_watcher.go, connor/antifraud/blacklist_watcher_test.go
This commit fixes the blacklist timer behavior on failures and successes.
Also, resetting the timer if a user was unblacklisted on the marker.
=> fix: proper blacklisting in Connor

util/xnet/resolve.go
This commit fixes a bug where our components, like Node and Worker resolved loopback devices using self-localhost-resolution.
This sometimes led to a problem on systems with disabled IPv6 but misconfigured /etc/hosts.
=> fix: properly discover loopback links

insonmnia/worker/volume/btfs.go
=> fix: proper BTFS initialization

insonmnia/worker/overseer.go, insonmnia/worker/plugin/plugin.go, insonmnia/worker/volume/btfs.go, insonmnia/worker/volume/driver.go
This commit activates network shaping for BTFS volume plugin.
Previously BTFS was run under separate bridge network, which was not connected with the network under which the deal tasks is being executed.
However now we are capable of performing task's network shaping under the constraints specified in supplier's order.
This commit changes the previous behavious with starting BTFS container under the same network with the task it manages, so network limitations should properly work.
=> feat: network shaping for BTFS

optimus/engine.go
This is required due to #1293.
=> fix: check BID identity level in Optimus

connor/antifraud/antifraud.go, connor/antifraud/config.go, connor/antifraud/log_processor.go, connor/antifraud/pool_processor.go, connor/antifraud/pool_processor_test.go, connor/antifraud/processor.go, connor/config.go, connor/engine.go, connor/types.go, etc/connor.yaml
This commit adds factory that builds log and pool processors.
This change allows us to easily attach new processors for different mining software and different mining pools.
Changes:
- Processor config now accepting the `Format` parameter, then we construct particular log readers and pool trackers according to the known type.
- The antifraud module now keeping ProcessorFactory instance and build processors when the task has been warmed-up.
- NilLogProcessor was dropped because of useless.
- More conveniently naming for existing log and pool processors.
=> refactor: construct anti-fraud processors with Factory

connor/config.go, connor/config_test.go, connor/engine.go, etc/connor.yaml
Chained with #1302
This commit adds method that generates env parameters for the container
according to configured token and mining pool. Also, user can override or extend
parameters using `engine.container_env` section in the config file.
=> refactor: build miner's env for pool and token

etc/optimus.yaml, optimus/cache.go, optimus/config.go, optimus/engine.go, optimus/worker.go
This commit allows Optimus to be executed in simulation mode, feching only specified orders from the marketplace.
Also fixed a bug when Optimus removed ask-plans in dry-run mode.
=> feat: simulation mode in Optimus

optimus/engine.go
This commit teaches Optimus to update auto-accepted price changes for deals.
Previously it only considers a price specified in ask-plan, not the real one, which may change during deal's lifetime.
=> feat: update price changes in Optimus

cmd/cli/commands/printers.go, proto/marketplace.go
To be consistent with #1277 we should print all prices as USD per hour.
=> refactor: print Deal's price per hour

connor/antifraud/antifraud.go, connor/antifraud/blacklist_watcher.go, connor/antifraud/blacklist_watcher_test.go, connor/antifraud/config.go, etc/connor.yaml
This commit fixes worker unblacklisting in the following way:
each tracked success decreasing the next possible blacklist step by the value of time in which task was correctly worked.
Each failure doubles a period of time in which a worker will be placed on the blacklist.
So if a worker is unblacklisted after the previous failure (1hr) and correctly work for 30 minutes, then, next blacklist time is 2hr minus 30 minutes.
=> fix: gradually decrease blacklisting in Connor

optimus/devices.go, optimus/devices_test.go
This fixes a bug when Optimus created ask-plan for orders that specified CPU cores benchmark with value greater than on the system.
=> fix: treat none benchmarks as min

insonmnia/dwh/processor.go, insonmnia/dwh/processor_test.go, insonmnia/dwh/server.go, insonmnia/dwh/setup_test.go, insonmnia/dwh/sql.go
Currently serialised certificates are stored inside profile records (which duplicates data, because certificates also have their own table). This PR removes serialised certificates from profiles table; certificates are now collected and serialised on the fly when serving `GetProfiles()` requests.
Motivation:
* Current state of affairs is weird;
* It will get even more weird if we [implement](https://sonmio.atlassian.net/projects/DEV/issues/DEV-921?filter=myopenissues) `CertificateUpdated` event processing.
=> chore: profile certificates refactoring

insonmnia/worker/volume/cifs.go
This fixes a bug, when specifying "vers" option for CIFS plugin resulted in error (seen in dmesg) that CIFS doesn't support "vers" option. This means that either too old cifs compatibility layer is installed or there is old smb server.
Now we just ignore unspecified "vers" option.
=> fix: support old samba servers

etc/optimus.yaml, optimus/config.go, optimus/engine.go, optimus/price.go, optimus/price_test.go, proto/insonmnia.go
This commit allows to specify either absolute or relative price threshold in Optimus.
=> feat: relative price threshold in Optimus

cmd/cli/commands/tasks.go, connor/antifraud/log_processor.go, connor/antifraud/log_processor_test.go, proto/log_reader.go
Implementing `Processor` interface for another container forces to do a lot of shameless copy-paste.
Taking into consideration that log parsers one differs from another almost only by logline parsing code,
it will be better to extract reusable parts and be able to swap only the code that directly works with log lines.
As this commit aimed to deal with copy-paste, I'd also move log reader to the separated package.
I cannot put logReader into the `utils` neither `xgrpc`, what would look pretty logical.
But we'll face an issue with cycle imports in that case.
=> refactor: extract common parts from LogProcessor

insonmnia/worker/server.go
Show DWH endpoint in `worker.GetStatus()` reply.
=> fix: show DWH status in worker status

insonmnia/npp/relay/monitor.go, insonmnia/npp/relay/server.go
Such error appeared when a server was under pressure. It worked the following way: a server announced itself and waited for a connection. When a client came it consumes that connection, causing `noPeerFound` errors for other clients that tried to resolve a server at the same time.
This commit fixes that behavior by putting clients into a short-waiting queue. In the future, we can improve this by checking whether a server was ever seen by Relay.
=> fix: no peer found error in Relay

cmd/connor/main.go, cmd/dwh/main.go, cmd/node/main.go, cmd/oracle/main.go, cmd/pandora/common.go, cmd/relay/main.go, cmd/rv/main.go, cmd/worker/main.go, insonmnia/dwh/config.go, insonmnia/logging/config.go, insonmnia/logging/logging.go, insonmnia/worker/acl_test.go
This commit extends logger config with the desired output.
Can be `stdout` (as it previously works), or it can be a path
to log file. Logs are written to the stdout will be colorized.
=> aux: allow to pass output to the logger

connor/config.go, connor/engine.go, etc/connor.yaml
This commit increases task starting timeout and makes it configurable.
Also, on `StartTask` retrying we'll check that previous attempt doesn't
really start a task.
=> fix: proper task start in Connor

connor/engine.go, connor/types.go, connor/x_test.go
This commit brings code that looks at the desired and existing order sets
which present on the Market and decide what orders should be removed.
Extra orders can appear when configured hashrate range was changed (by decrease).
=> feat: remove extra orders in Connor

insonmnia/node/config.go, insonmnia/node/mod.go, insonmnia/node/options.go, insonmnia/node/server.go, insonmnia/npp/dial.go, insonmnia/npp/options.go, insonmnia/npp/puncher.go, insonmnia/ssh/config.go, insonmnia/ssh/proxy.go, insonmnia/worker/config.go, insonmnia/worker/container.go, insonmnia/worker/options.go, insonmnia/worker/server.go, insonmnia/worker/ssh.go, vendor/golang.org/x/crypto/ssh/agent/client.go, vendor/golang.org/x/crypto/ssh/agent/forward.go, vendor/golang.org/x/crypto/ssh/agent/keyring.go, vendor/golang.org/x/crypto/ssh/agent/server.go, vendor/vendor.json
This allows to perform SSH'ing into containers by specifying only deal
and task identifiers independing of whereever those containers are being
run.
This is done by proxying the traffic through local Node.
The idea is to hijack to incoming TCP connection with further resolving
the real endpoint of a Worker where a container is being run by deal ID
using NPP with further traffic forwarding directly into it. The Worker
may not be having a public IP address.
=> feat: SSH into containers through Node

connor/engine.go
such problem occurs in the following conditions: Connor detects price deviation and starts replacing orders, also it starts to close non-profitalbe deals. When the deal is closed, a worker on another side can pick the order that we schedule for cancellation. This order is turned into a deal that immediately will be closed because of the low price. So this shitfall will perform until all of the orders isn't replaced. This commit fixes that behavior: now Connor checks that the cancel chan is empty before really closing an active deal.
=> fix: proper deal closing when price is changed

insonmnia/worker/overseer.go, insonmnia/worker/server.go, proto/worker.pb.go, proto/worker.proto
- Removed several stale TODOs, which was introduced
during previous large refactorings.
- Method's docstrings fixed to match the golang's standards.
- Import and variable names clashing avoided.
=> chore: worker's code cleanup

insonmnia/worker/overseer.go
Currently overseer allows users to push images with repo & tag info, which means that pushed images can overwrite existing containers with same repo & tag values (and that's a security breach). This PR removes repo & tag info from pushed images so that sha256 is always used as image identifier.
@antmat PTAL
=> fix: remove repo & tag from uploaded image

connor/antifraud/processor.go, connor/config.go
This commit adds null log and pool processors for Connor's anti-fraud module.
It can be used for testing purposes or if the user wants to run custom (non-mining) tasks
with external quality tracking.
=> feat: disabled anti-fraud modules in Connor

optimus/engine.go, optimus/engine_test.go, proto/ask_plan.go
During learning the following situation may appear: there are a set of orders that are planned to replace existing ones, but some of them are technically equal, i.e. have the same resources, price, and duration. Current Optimus just replaces ask-plans, which results in deal cancellation, which is not good.
This commit teaches Optimus to detect duplicate orders when it's time to replace ask-plans with more profitable ones and not to touch them if any.
=> feat: detect duplicate orders in Optimus

insonmnia/worker/ssh.go, insonmnia/worker/ssh_test.go
This commit fixes couple bugs introduced in #1281.
1. Failed to start a task without providing ssh pubkey.
2. Marshalling an empty pubkey crashes worker.
=> fix: proper (un)marshaling for empty SSH keys

insonmnia/resource/pool.go, insonmnia/worker/overseer.go, insonmnia/worker/overseer_test.go, insonmnia/worker/server.go
This commit fills the `AllocatedResources` field from the deal's ask-plan.
Actual resources info gives an ability to show what part of deal's resources are acquired by task, at least what GPUs is used.
=> fix: show allocated resources in TaskStatus

connor/antifraud/antifraud.go, connor/antifraud/config.go
USE ONLY FOR DEBUGGING PURPOSES AND NEVER USE IN PRODUCTION.
Connor debugging will be pretty easy if deals with test suppliers in the Testent will not be closed (because we should remove it from the blacklist, restart Connor, restart tasks, etc..
and it does the whole development process really sucks).
=> aux: debug whitelist for Connor

insonmnia/node/server.go, insonmnia/ssh/proxy.go
This commit fixes race when Node starts with some failed condition, for example, when SSH port is occupied, and then hangs forever.
=> fix: Node hanging on failed startup

insonmnia/npp/relay/server.go
This should eliminate some sockets in CLOSE_WAIT state.
=> fix: properly close read/write part of sockets in Relay

connor/config.go, connor/types.go, connor/types_test.go, connor/x_test.go, etc/connor.yaml
This commit adds an ability to set counterparty address and place orders only for the required supplier. Also, migration code was added.
If a user wants to change non-main benchmark or set counterparty or change netflags,
Connor should be able to detect, that new requirements is changed.
It reached with partial order hashing when we decide to restore existing order or not.
=> feat: counterparty address for Connor's orders

insonmnia/worker/server.go, insonmnia/worker/ssh.go
This commit fixes invalid identity level verification while performing SSH access to a container using NPP API.
Previously an identity level of ask-plan was checked, while actuially it must be the consumer's level checked.
Closed #1421.
=> fix: proper identity level check in worker SSH

optimus/config.go, optimus/engine.go
This commit forces Optimus to write why it has excluded orders from the candidates' list. Note, that this will dramatically increase logging output in exchange for more clean understanding why your favorite order was excluded.
=> feat: verbose filtering in Optimus

util/netutil/net.go
For some unknown reasons, Go developers keep IPv4 addresses in a slice of size 16(!). It's so logical, yes.
Just take a look at this another example of clean go architecture:
```go
func IPv4(a, b, c, d byte) IP {
p := make(IP, IPv6len)
copy(p, v4InV6Prefix)
p[12] = a
p[13] = b
p[14] = c
p[15] = d
return p
}
```
=> fix: properly detect IPv4 addresses

etc/worker.yaml, insonmnia/worker/options.go, insonmnia/worker/ssh.go
This commit simplifies SSH server configuration on a Worker by deprecating "private_key_path" option in "ssh" section. Now SSH key is generated at Worker start up and cached in boltdb.
=> feat: generate SSH key instead of require

connor/price/cmc_wtm.go, connor/price/cmc_wtm_test.go, connor/price/utils.go
This commit fixes calculation algo for XMR.  Also, signature of the PriceProvider's `calculateFunc` has been changed because we want to use all available token params, not only reward and net difficulty.
=> fix: proper formula for XMR price calculation

insonmnia/worker/acl.go, insonmnia/worker/server.go
This commit fixes a bug when the gRPC server running with WorkerManagement methods available, but the worker is not fully initialized. Thus calling methods like `debug-state` or` free-resources` lead to random  crashes of the worker. To prevent this we must limit access to this handles with ACL.
=> fix: limited access to the status server on startup

connor/antifraud/log_processor.go, connor/antifraud/processor.go, connor/config.go
This commit adds a new log processor type for Connor's anti-fraud module.
Brand new processor able to read logs from the xmrig miner, which is used to mine Monero (cryptonight) on CPUs.
=> feat: Connor's log processor for xmrig

Makefile, etc/worker.yaml, insonmnia/worker/acl.go, insonmnia/worker/acl_test.go, insonmnia/worker/config.go, insonmnia/worker/server.go, insonmnia/worker/whitelist.go
This PR introduces acl which checks KYC level and allow only users of specific level to push custom inages on worker. Also it's made configurable and it is reused in whitelist configuration.
closes #1434
=> refact: restrict image push with KYC level

insonmnia/worker/overseer.go, insonmnia/worker/server.go
`TaskStop` should not make worker forget about the task (i.e., worker should know about stopped tasks after restart if deal is still active).
=> fix: keep container info after task stop

insonmnia/worker/container.go, insonmnia/worker/network/tinc_tuner.go
This PR fixes ability to add tinc network alongside shaped interface. As docker does not accept multiple networks during container creation we do connect them afterward.
=> fix: properly initialize tinc network

connor/engine.go
This commit extends Connor's logger (bounded to a deal) with the supplier eth address.
Also, use proper logger instance in the `startTaskOnce` method.
=> fix: log the supplier's address in Connor

connor/antifraud/log_processor.go, connor/antifraud/log_processor_test.go
This commit fixes several issues with log processor:
- Wrap calculated hashrate value with atomic to make it thread-safe.
- Perform initializing tick for EWMA.
- Add timestamps for stored logs.
- Read logs with tail. It prevents us from reloading full task log when Connor restarts or when connection was lost and Connot should start read logs again.
=> fix: proper log processor for Connor

util/xdocker/reference.go, util/xdocker/reference_test.go
This commit fixes xdocker.Reference marshalling in the way it can be used via json and yaml encoders.
=> fix: proper xdocker.Reference marshalling

connor/config.go
=> fix: remove extra benchmark from Connor's config

insonmnia/worker/server.go, util/xgrpc/options.go
This commit allows restricting Worker and Node services usage by specifying rate limiter interceptor, which can be configured for taking in action both global and precise settings - for each method differently.
This is required to avoid some dumb DOS attempts, however, not ideal.
The idea is to keep RPS counter for each remote peer that is identified by ETH address, which we can extract from the request. The counter has EWMA internally, which is good for an unpredictable load profile. When this EWMA exceeds the specified threshold an "Unavailable" error is returned.
Closes #1495.
=> feat: gRPC rate limiter

Makefile, cmd/cobra.go, cmd/connor/main.go, cmd/dwh/main.go, cmd/node/main.go, cmd/optimus/main.go, cmd/oracle/main.go, cmd/relay/main.go, cmd/rv/main.go, cmd/worker/main.go
This commit brings a minor rethinking about how we define our main executables.
First, there is no need to define "magic" global variables, such as "appVersion" and other flags, that are used in our CMD internals - all is done automatically. The required parameters can be extracted from the new "AppContext" argument, that is passed to all runner functions.
Then, there is no need to specify the application name - now it is taken from the actual file name, and it means that it will contain sometimes required suffixes, such as "_linux_x86_64".
=> refactor: simplify main definition

insonmnia/worker/server.go
We already have request logging, which is generic and log any incoming
request before it even passes the authorization step.
This commit drops the excess line while fetching task logs.
=> refactor: drop excess log

insonmnia/worker/options.go
This allows to see why a Worker's matcher failed to open a deal, instead
of just "transaction failed".
=> feat: activate nice market API on Worker matcher

cmd/cli/commands/common.go, cmd/cli/commands/login.go
This commit adds able to pass `--password=topsecret` flag for `sonmcli login` command.
Useful for auto-installer script.
=> feat: password flag for sonmcli login command

cmd/cli/commands/printers.go
Closes #1521
```
CPU: 2 cores at 1 sockets
Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
Benchmarks:
cpu-cryptonight: 40
cpu-sysbench-multi: 5406
cpu-sysbench-single: 30677
cpu-cores: 2
```
=> chore: print CPU model in worker devices cmd

util/xgrpc/client.go, util/xgrpc/options.go
Node and other servers under the medium/high load should no longer suffer from a memory leak.
Internals:
- For a long time, we used the in-memory recorder for tracing. However, it doesn't make sense, because internally it just saved all spans without reason and cleaning up. Now we use a no-op recorder because seems everything works fine without span recording.
=> fix: memory leak in Node and everywhere

optimus/market.go, optimus/market_cache.go, optimus/predictor.go, proto/marketplace.go
Bid price predictor is now trained on BID orders that were successfully converted into deals. This should reduce the deviation between the predicted price and the actual one.
Also, Optimus is now trained on BID orders, while previously all active orders were used.
Internals:
- Renamed "optimus/cache" to "optimus/market_cache" for better showing its aim.
- Added setters for some benchmarks.
Analyzing currently pushed orders on the marketplace shows the following statistics on deviation, which is calculated as `predicted_price / price`:
Before:
```bash
Mean     = 4.167913477297036; 
Variance = 90.5015091172015; 
StdDev   = 9.513228112328722; 
Median   = 1.2999912360382637
```
After:
```bash
Mean     = 1.1611107487160566; 
Variance = 0.3367232091146091; 
StdDev   = 0.5802785616534606; …
```
=> fix: reduce bid price predictor deviation

connor/engine.go, connor/state.go
We can get a race when `waitForDeal`'s timer ticks after the `waitForExternalUpdates`'s one.
Deal will be traited as externally opened and its processing will be started. Then waitForDeal will make a tick, detected new deal opened for known order and add the same deal to the processing. This commit adds check that deal is not in the state storage before starting the processing routine.
=> fix: check for deal existance before processing

connor/config.go, connor/engine.go, etc/connor.yaml
This commit adds config option that change `restoreMarketState` behavior.
If `no_cancel` parameter is enabled, Connor will adapt orders that not fits in target orders set.
=> feat: adapt extra orders in Connor

cmd/cli/commands/client.go, cmd/cli/commands/common.go, cmd/cli/commands/printers.go, cmd/cli/commands/tasks.go, cmd/cli/commands/worker_tasks.go, insonmnia/node/server.go, insonmnia/node/server_test.go, insonmnia/node/services.go, insonmnia/node/tasks.go, insonmnia/node/worker.go, proto/node.proto, util/xgrpc/options.go
This PR deprecates Node TaskManagement service and replaces it with Worker service. 
All requests in node are proxied in interceptors as is, workere selection is based via dealID passed via deal context variable.
=> refactor: deprecate TaskManagement service

connor/antifraud/config.go, connor/antifraud/log_processor.go, connor/antifraud/log_processor_test.go, connor/antifraud/pool_processor.go, connor/antifraud/processor.go, connor/config.go, etc/connor.yaml
This commit removes particular log parser with a single one with a subset of settings which can be applied to (almost) any logs with a number in their fields.
Log reader now has 3 options related to logline analyzing:
1. String pattern to detect line with logs. E.g: line that has 'Total speed' in it will be analyzed, if it doesn't - we'll skip this line.
2. Field number in line. Describes which position in a string is a numeric value that shows task quality (hash rate, actually).
3. The multiplier for parsed value. Used when a field contains the value in KHash/s or MHash/s. Use `1` if the multiplier is not applicable for the value.
=> feat: generalized log parser for Connor.

insonmnia/node/worker.go, util/rest/server.go, util/xgrpc/method.go, util/xgrpc/options.go
This commit slighty changes the REST server behavior by forcing to return errors as JSON for the sake of consistency.
Previously all errors were returned as a plain text. Now set set the application/json header and wrap the error into a JSON object.
Also the encoding/decoding logic was slightly changed - now if a Node is configured into secure mode it will return all responses as encoded byte array. This was done for symmetry, because one can have a client with encoder, and it expects the encoded response. Previously if a request failed in URI parsing stage a plain-text reply was returned. That was unexpected and completely helpless for people that try to work with secure Node in insecure manner. The error says something, but anyway you're unable to do anything with the Node unless you …
=> feat: return REST errors as JSON

insonmnia/worker/container.go, insonmnia/worker/overseer.go, insonmnia/worker/server.go
This PR fixes behaviour when containers are being concurently removed in
event watcher, resulting in error in OnDealFinish call
(e.g. inablility to push already removed container to registry).
If this situation took place on startup - worker would fail to start.
=> fix: proper worker startup, removing cocncurent container cleanup.

util/rest/server.go
This commit adds ability to set worker header via HTTP 1.1 request.
Header will be used by WorkerManagement interceptor to create connection.
=> fix: forward meta headers to worker interceptor

insonmnia/npp/listener.go
This commit fixes a thread-safety issue while handling Rendezvous errors. Previously the puncher was reset in another thread, which might cause a race condition, leading to unrecoverable error returned from an acceptor and further worker stop. Now all of this is done in the same thread when the puncher is handled.
=> fix: race condition while resetting puncher

blockchain/client.go, blockchain/client_test.go
Fix behaviour for parsing `To` field according to [web3 json rpc scpec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt)
> to: DATA, 20 Bytes - address of the receiver. null when it's a contract creation transaction.
This fix affect contract' creation transactions.
=> fix: getTransactionReceipt To field unmarshalling

blockchain/source/.soliumrc.json
Turn off some harmfull or useless rules:
* `error-reason` - required error messages for all `require` ops.
* `security/no-block-members` - don't use of timestamp.
=> aux: change solium linter rules

go.mod, go.sum, insonmnia/node/mod.go, insonmnia/node/options.go, insonmnia/ssh/crypto.go, insonmnia/ssh/proxy.go, insonmnia/worker/options.go, insonmnia/worker/ssh.go
Now it is possible to SSH to a Worker using Node proxy, which is especially useful for debugging. Internally it works the same way as we did SSH into containers, except the user identity, which is now can be a public ETH address of a Worker.
https://asciinema.org/a/XAY5ll7Mz4FsfdmlOkC9w4QuP
=> feat: SSH on Worker host

optimus/engine.go, proto/insonmnia.go
Currently after the optimization process is done, Optimus replaces some of ask-plans with the new ones, dropping currently running deals, which causes painful races in the entire SONM network - all running bots are greedily engaged on a new profitable order, but only one of them succeeds.
The new logic in the Worker should eliminate this race, we just support it in Optimus. Now it will cancel ask-plans only if there is no deal associated with it, delegating other plan management logic to the Worker.
=> feat: Optimus should no longer remove active plans

optimus/engine_genetic.go
If a genetic model in Optimus fails to find a genome that has non-zero fitness it no longer interrupts the entire optimization process, instead writing a log message.
This should also fix an issue in the price predictor.
=> fix: failed genetic model should not interrupt optimization

insonmnia/hardware/disk/disk.go, insonmnia/worker/metrics/metrics.go, insonmnia/worker/server.go
We must avoid two syscalls to gather disk space. Also will be useful for worker monitoring suite.
=> feat: added used bytes for the disk benchmark

cmd/lsgpu/main.go, insonmnia/worker/gpu/dri.go
Now we're trying to find hwmon path on the device initialization.
If we can do this, the monitoring interface for this card became available.
The `Monitoring` method reads some data from the `/sys/dev` internals, all behavior has been ported from the [ROC-smi tool](https://github.com/RadeonOpenCompute/ROC-smi).
=> feat: ability to collect metrics from DRI devices

debian/control
=> fix: add mount.cifs package to debian dependencies

insonmnia/resource/plan_pool.go
Subtraction of committed spot ask-plans was forgotten resulting in inappropriate available resources calculation. This sometimes led to a situation where the same resource was sold multiple times.
Now everything should work properly.
WARNING: we recommend everyone to update workers, otherwise, they may get blacklisted.
=> fix: properly eject spot committed ask-plans

insonmnia/npp/rendezvous/server.go
There is a situation where a client no longer awaits the resolution result, while there is actually alive server who is ready to establish the connection. In this case the communication channel becomes overflowed (because of its capacity of 1), which leads to a deadlock.
This PR fixes that by increasing the capacity to 2. Not the best solution, but for now at least it fixes deadlocking.
=> fix: deadlock in Rendezvous server

insonmnia/npp/net.go, insonmnia/npp/rendezvous/server.go, insonmnia/npp/rv.go, util/xgrpc/options.go
Previously we tried to set up TCP keepalive option to ensure that even
if the NAT closes the connection we're still able to detect it properly.
However, the library we use to configure SO_REUSEPORT option just
ignores any keepalive specifications. So we set it, but nothing worked
properly. All this results in a situation when sometimes during either
network instability or NAT conntrack configurations the Rendezvous
server properly detected whether a Worker is disconnected, but the
Worker itself - was not, otherwise it would try to reconnect.
This change replaces TCP keepalives with HTTP/2 ping frames, which
are more portable and works in userland.
=> fix: replace TCP KA with HTTP2 pings to Rendezvous

cmd/cli/commands/printers.go
This commit adds the `type` field into the `sonmcli deal list` command.
The type indicates that the current user is selling or buying resources in that deal.
Closes #1445
=> feat: show deal type in deal list cmd

etc/worker.yaml, insonmnia/worker/config.go, insonmnia/worker/server.go
We must provide metrics collection address to properly set ACLs in worker
and also be able to collect metrics from whole SONM network.
=> feat: metrics collection addr and ACL for worker

Makefile, cmd/cli/main.go, cmd/cobra.go, cmd/node/main.go, cmd/optimus/main.go, cmd/worker/main.go, go.mod, go.sum, insonmnia/version/version.go, insonmnia/version/version_test.go
Currently we often have a situation when our clients (both suppliers and customers) don't know whether a new version of the platform has been released. To avoid this we've done a simple console notification as a warning about whether it's time to update.
=> feat: version checking for core components

optimus/worker.go
This hotfix restores Optimus's ability to remove plans without immediate exiting.
=> fix: properly remove ask plans in Optimus

util/xgrpc/options.go
Currently we print stacktraces for any error that is logged. This is
actually useful, but there are cases where it's more annoying than
useful. For example - messages after RPC calls, where stacktraces are
the same and completely useless.
After this change we should no longer print those stacktraces in audit
logs.
=> fix: reduce noise while logging RPC calls

insonmnia/npp/puncher_quic.go, util/xnet/quic.go
This fixes the memory leak in Rendezvous, Node and Worker components.
=> fix: close QUIC sessions and streams

insonmnia/npp/rendezvous/server.go
Previously in a client tries to resolve remote server in the Rendezvous and that server is absent - the client is hanged for some period of time. This was reported as inconvenient because if such server has never been published it is meaningless even to try to wait for it.
Moreover, when a server is resolved it cleans its announce mapping until the next announce, which causes flapping in the info handler.
Now all servers are considered live and will not be removed from the info handle if they are capable to reannounce themselves in ~30s. Otherwise the immediate "no peer found" error will be returned to the client.
=> feat: TTL for servers in Rendezvous

insonmnia/worker/gpu/metrics.go, insonmnia/worker/gpu/radeon_tuner.go
Now we have a situation when we have on-board and external video on the machine.
Embedded graphics adapter also can be detected as DRI device, but does not provide any metrics interface.
For GPU tuner plugin we're using a crutch: detecting device twice, via DRI and OpenCL, then comparing the results.
This commit re-use that code to collect cards for monitoring interface.
=> fix: properly detect for "red" cards in monitoring handler

insonmnia/worker/gpu/metrics.go, insonmnia/worker/gpu/radeon_tuner.go
Introduced in #1776
Changelog: exclude
=> fix: randomly place asterix char before the structs

optimus/engine.go
Reduced default branch-bound model thresholds. Switch for default optimization method while calculating current worker's price.
=> fix: memory leak in Optimus

connor/engine.go
Checking that the error is temporary instead of notifying about success via a boolean flag
is bit more humaneness and eye-friendly.
=> refactor: temporary errors instead of bool flags

Makefile
It is required to enable OpenCL support and be able to detect GPUs using it.
=> aux: build lsgpu with GPU_TAGS

blockchain/api.go, blockchain/types.go, insonmnia/dwh/processor.go
This commit fixes random "out of sync" state reaching when there are no events has been produced in the chain.
Now if the blockchain's `GetEvents` method returns no logs entities - we're emitting `NoEventsData` event which is processing as any other events. Event triggers an update of the lastBlock counter, and the "out of sync" state does not appear.
Closes #1689.
=> fix: proper reaching "out of sync" state

insonmnia/dwh/server.go
At least we also should notify a user about the "out of sync" state.
=> fix: enable interceptor for REST interface on DWH

insonmnia/worker/network/tc/ifb.go
Failing while initializing ifb device resulted in printing "Exit status 1", which is not obvious to understang what's going on. Now we will report at least which command we're trying to execute.
=> fix: human-readable TC initialization error

insonmnia/worker/overseer.go, insonmnia/worker/salesman/options.go, insonmnia/worker/salesman/salesman.go, insonmnia/worker/server.go
This PR introduces timeouts during deal cancellation in order not to hang forever if something(e.g. in docker) goes wrong
=> fix: do not hang on deal cancellation

insonmnia/worker/salesman/salesman.go, util/multierror/error.go
Fixxed bug with task cancellation:
* process ask-plan which are pending for deletion in a usual pipeline to update order info in case ask-plan can not be deleted right now
* return proper type from ErrorOrNil function to fix this https://golang.org/doc/faq#nil_error behaviour
=> fix: proper error type in ErrorOrNil

util/xgrpc/options.go
It was implemented for inspection service, but no longer required, since it has a more convenient way to subscribe for authorization change events.
Fixes inability to use "TaskLogs" handle.
P.s. Worker logs subscription still works, I checked.
=> fix: revert per-chunk stream authorization

cmd/sonmmon/main.go
=> Preventing division by zero panics

insonmnia/worker/gpu/volume_plugin.go
Now we're hardlinking .so files and other nvidia related stuff
into the volume. This way isn't working when /var is present in another partition,
we must fallback to Copy in such case.
=> fix: use LinkOrCopyStrategy to provision nvidia volumes

insonmnia/worker/gpu/utils.go
Now we're storing whole information required to mount single GPU into a container inside the `sonm.GPUDevice` structure. and now we can turn up into a situation, when we're trying to mount more than one GPU with the same type. The Tuner will try to attach more than one (absolutely same) volume to the container. In that case, it will lead to the container' start failure.
This PR fixes that behavior by collecting proposed mount points into the set, and then applying only non-repeated ones.
=> fix: avoid duplicated driver volumes for GPUs

go.mod, go.sum
This pr fixes incorrect `github.com/libp2p/go-reuseport` dependency definition.
It's replaces automatically after every build.
=> fix: gomod reuseport replacement

util/xgrpc/server.go
Before the only gzip compression was always used, which caused troubles with gRPC clients without compression support.
This commit allows selecting how to compress the response depending on request compression type.
=> feat: multiple gRPC compressions

util/xgrpc/options.go
Previously streaming gRPC authorization always ignored the first
chunk for the incoming stream and checked for others. This is wrong for
methods which stream only back because the entire authorization
mechanism is suppressed at all.
This commit fixes such behavior by forcing the auth routing to check for
the first incoming message.
=> fix: wrong streaming authorization check

connor/antifraud/antifraud.go
Actually this function returns no error at all.
=> chore: tune function signature in connor

insonmnia/dwh/setup_test.go
This PR fixes behavior with dwh test suite:
* add required for run `POSTGRES_PASSWORD` environment
* returns an error when Postgres not started any times, not null
* format touched file imports
=> fix: dwh tests

Makefile, appveyor.yml, debian/changelog
* Added: allow to specify pwd in secexec (#1901).
Also the usage of "secexec" has been slightly changed: now the executable and
its arguments must be specified after "--".
For example: secexec /etc/secexec -- /bin/ls -lith.
* Added: watch for keystore in sysinit.
* Fixed: more nvidia related .so files for volumes (#1907).
Found out that we're skipping a lot of useful nvidia's .so files.
This PR adds all of them to the docker volume.
Based on the content of NVIDIA-Linux-x86_64-440.82.
To keep the list up-to-date in the future:
1. download the latest version on drivers;
2. unpack them without installing: "./NVIDIA-Linux-x86_64-XXX.YY.run
--extract-only";
3. list .so and update the list in "insonmnia/worker/gpu/nvidia_tuner.go";
Don't forget to remove versions and .0 from file names;
4. ??? …
=> version: bump - 0.4.31
