insonmnia/miner/config.go
insonmnia/miner/config_test.go
insonmnia/miner/server.go

Related to #24 
Skip discovery if hub ip is set in config file

Use hub addr from config

---

insonmnia/miner/server.go

```bash
esafronov@esafronov:~/go/src/github.com/sonm-io/core|chore/renaming⚡
⇒  ./sonmcli --addr=localhost:10001 miner list
Miner: [::1]:50834
tasks:
esafronov@esafronov:~/go/src/github.com/sonm-io/core|chore/renaming⚡
⇒  ./sonmcli --addr=localhost:10001 task start "[::1]:50834" "cocaine/cocaine-core"
Starting "cocaine/cocaine-core" on miner [::1]:50834...
ID e46eb0d5-c0ea-4b31-9664-9935f84e1700, Endpoint [10053/tcp->95.31.19.243:32773]
esafronov@esafronov:~/go/src/github.com/sonm-io/core|chore/renaming⚡
⇒  ./sonmcli --addr=localhost:10001 miner status "[::1]:50834"
Miner tasks:
ID: e46eb0d5-c0ea-4b31-9664-9935f84e1700
CPU: 35648419
RAM: 2MB
```
Includes #32 (and closes #32), so merge this after the specified PR.

fix: use task id in info

---

insonmnia/hub/miner_ctx.go
insonmnia/hub/server.go

Restore MinerStatus behaviour as it previously was.
@sshaman1101 @noxiouz @3Hren PTAL

fix: restore MinerStatus behaviour

---

insonmnia/miner/builder.go
insonmnia/miner/config.go
insonmnia/miner/container.go
insonmnia/miner/gpu_tune.go
insonmnia/miner/overseer.go
insonmnia/miner/overseer_test.go
insonmnia/miner/server_test.go

It requires to have nvidia-docker-plugin on the host plugged to Docker daemon

miner: introduce GPU support

---

insonmnia/miner/builder.go
insonmnia/miner/config.go
insonmnia/miner/container.go
insonmnia/miner/overseer.go
insonmnia/miner/server.go
insonmnia/miner/server_test.go
insonmnia/miner/ssh.go
miner.yaml
vendor/github.com/anmitsu/go-shlex/LICENSE
vendor/github.com/anmitsu/go-shlex/README.md
vendor/github.com/anmitsu/go-shlex/shlex.go
vendor/github.com/docker/docker/pkg/stdcopy/stdcopy.go
vendor/github.com/gliderlabs/ssh/LICENSE
vendor/github.com/gliderlabs/ssh/README.md
vendor/github.com/gliderlabs/ssh/agent.go
vendor/github.com/gliderlabs/ssh/circle.yml
vendor/github.com/gliderlabs/ssh/conn.go
vendor/github.com/gliderlabs/ssh/context.go
vendor/github.com/gliderlabs/ssh/doc.go
vendor/github.com/gliderlabs/ssh/options.go
vendor/github.com/gliderlabs/ssh/server.go
vendor/github.com/gliderlabs/ssh/session.go
vendor/github.com/gliderlabs/ssh/ssh.go
vendor/github.com/gliderlabs/ssh/tcpip.go
vendor/github.com/gliderlabs/ssh/util.go
vendor/github.com/gliderlabs/ssh/wrap.go
vendor/vendor.json

Early version without authentication.
@3Hren @noxiouz @Sokel @sshaman1101 
PTAL

feat: ssh embedded server for container access

---

.gitignore
Makefile
README.md
appveyor.yml

Related to #79; Trying to collect all stuff to build windows version of the cli

appveyor experiments

---

Makefile
insonmnia/gateway/gateway.go
insonmnia/gateway/gateway_linux.go
insonmnia/gateway/gateway_nonlinux.go
insonmnia/gateway/pool.go
insonmnia/gateway/pool_test.go
insonmnia/hub/miner_ctx.go
insonmnia/hub/router.go
insonmnia/hub/router_linux.go
insonmnia/hub/router_nonlinux.go
insonmnia/hub/server.go
insonmnia/miner/marshal.go
insonmnia/miner/overseer.go
vendor/github.com/tehnerd/gnl2go/LICENSE
vendor/github.com/tehnerd/gnl2go/README.md
vendor/github.com/tehnerd/gnl2go/adr_conv_utils.go
vendor/github.com/tehnerd/gnl2go/gnl2go.go
vendor/github.com/tehnerd/gnl2go/ipvs.go
vendor/gopkg.in/oleiade/lane.v1/LICENSE
vendor/gopkg.in/oleiade/lane.v1/README.md
vendor/gopkg.in/oleiade/lane.v1/deque.go
vendor/gopkg.in/oleiade/lane.v1/doc.go
vendor/gopkg.in/oleiade/lane.v1/pqueue.go
vendor/gopkg.in/oleiade/lane.v1/queue.go
vendor/gopkg.in/oleiade/lane.v1/stack.go
vendor/vendor.json

This PR introduces traffic routing for Miners under the firewall using IPVS.
TBD:
Closes #91.

feat: smart routing via IPVS

---

hub.yaml
insonmnia/hub/config.go
insonmnia/hub/miner_ctx.go
insonmnia/hub/server.go

This commit allows to disable Hub as a gateway. Intended for testing environments and not to break brains configuring linux internals to make things work.

feat: make gateway optional

---

cmd/cli/commands/interactor.go
insonmnia/hub/miner_ctx.go
insonmnia/hub/server.go
insonmnia/miner/builder.go

related to #98 
Im gonna add some metrics and mark all traffic  in the future

feat: use gzip to reduce network usage hub/miner/cli

---

Makefile
cmd/hub/main.go
cmd/miner/main.go

This PR adds `--version` flag to hub and miner

feature: hub and miner version

---

insonmnia/miner/container.go
insonmnia/miner/gpu_tune.go

This PR fixes NVidia volumes binding and cgroups permissions assigning for video-devices.

fix: video devices

---

insonmnia/hardware/gpu/cl.go

This PR fixes a build on Linux with OpenCL enabled;

fix: add cgo tags for linux

---

insonmnia/hub/server.go

fix: proper dead miners detection

---

insonmnia/hub/server.go

fixes https://github.com/sonm-io/core/issues/142

fix: hanging on the stop

---

blockchain/api.go
cmd/marketplace/main.go
fusrodah/examples/miner/main.go
insonmnia/hub/server.go
insonmnia/miner/container.go

This PR fixes some mistypes found by [Go Report Card](https://goreportcard.com/report/github.com/sonm-io/core)

chore: fix misspell

---

insonmnia/hub/cluster.go
insonmnia/hub/config.go

Chained with https://github.com/sonm-io/core/pull/173
Make all cluster ttls and keys configurable

Configurable cluster

---

hub.yaml
insonmnia/hub/cluster.go
insonmnia/hub/config.go

This PR add better config example, which works out of box and fixes cluster behaviour when working with boltdb

fix: support event watcher via boltdb

---

hub.yaml
insonmnia/hub/cluster.go

fix: misprint, excess logging

---

blockchain/api.go
cmd/cli/commands/node_market.go
insonmnia/node/market.go
insonmnia/node/server.go
insonmnia/node/tasks.go

This PR adds Deal creation when BID order is placing on the marketplace.
Added: 
- call blockchain API from the local node on order placement;
- load an Eth keys every "market" sub-command;
Changed: 
- OpenDeal() now receive pb.Deal model (instead of tons of func params)

Fix: create deal while placing Marketplace's BID Order

---

accounts/identity_test.go
blockchain/api.go
cmd/cli/task_config/config.go
cmd/cli/task_config/config_test.go
fusrodah/fusrodah.go
insonmnia/hub/cluster.go
insonmnia/hub/miner_ctx.go
insonmnia/hub/server.go
insonmnia/locator/server.go
insonmnia/miner/overseer.go
insonmnia/miner/pull_utils.go
insonmnia/miner/server_test.go
util/util.go

fix: style issues

---

cmd/locator/main.go
cmd/marketplace/main.go
insonmnia/locator/server.go
insonmnia/locator/server_test.go
insonmnia/marketplace/server.go
insonmnia/marketplace/server_test.go

This PR enables logging for Locator and Marketplace service.

marketplace and locator logging

---

hub.yaml
insonmnia/hub/config.go
insonmnia/hub/config_test.go
insonmnia/hub/eth.go
insonmnia/hub/eth_test.go
insonmnia/hub/market.go
insonmnia/hub/server.go

This PR implements interaction with Eth and Market on Hub.

hub etherum integration

---

Makefile

small fix for makefile in case of unexisting bin folder

fix: makefile proper install

---

insonmnia/hub/cluster.go

This PR fixes generating ipv6 endpoints for cluster announcements

fix: proper ipv6 endpoints

---

insonmnia/node/market.go
insonmnia/node/server.go
insonmnia/node/tasks.go

This PR fixes deal creation process into node;
Added intermediary status for order handler. Now the deal for an order must be approved on Hub side. Then deal will be marked as ready-to-use for the buyer.

Node: wait for approved deal

---

insonmnia/miner/crypto.go

fix that fixes previous fix

---

task.yaml

Restores default image: Travis can't spool from docker repo (eventually).

fix: restored default image

---

cli.yaml
cmd/cli/config/config.go
node.yaml

CLI and node  now use project-local keystore.

feat: default local keystore for node and cli

---

insonmnia/structs/slot.go

subj, inner was previously unexported field

fix: proper slots marshalling

---

cmd/cli/commands/tokens.go

Related to discussion into the office.

chore: update the "approve" method help text

---

cmd/cli/commands/login.go

fix: cli login output

---

hub.yaml
insonmnia/hub/config.go
insonmnia/hub/server.go
insonmnia/hub/server_test.go
insonmnia/hub/whitelist.go

feat: whitelist implementation

---

insonmnia/hub/acl.go
insonmnia/hub/server.go

Some strange code. Your suggestions are appreciated.

fix: hub management ACL

---

insonmnia/hub/config.go
insonmnia/hub/server.go
insonmnia/hub/whitelist.go
util/ticker.go

feat: update whitelist on timer

---

insonmnia/hub/cluster.go
insonmnia/hub/server.go

fix: proper entities sync (finally!)

---

insonmnia/hub/server.go

This PR fixes possible crashes of the Hub when there are some problems with Deal accepting;

fix: possible Hub crashes on deal  accept error

---

cmd/cli/commands/printers.go
insonmnia/miner/server.go

* Task status now contains miner's public IPs.

fix: set proper public IPs to task status

---

insonmnia/hub/server.go

subj
@noxiouz @sshaman1101 PTAL
Did not tested yet
Upd: tested minimal case

feat: synchronize deals into cluster

---

insonmnia/hub/acl.go
insonmnia/hub/acl_test.go
insonmnia/hub/server.go
insonmnia/structs/order.go

subj, @3Hren @noxiouz @Sokel @sshaman1101 @oopcode PTAL anybody

refact: use deals from Hub for Deal Auth

---

cmd/cli/commands/hub_order_test.go
cmd/cli/commands/printers.go
cmd/cli/task_config/slot.go
insonmnia/hub/scheduler.go
insonmnia/structs/slot.go
insonmnia/structs/slot_test.go
order.yaml
slot.yaml

This PR removes rating from the slot comparison;

Fix: remove rating

---

insonmnia/locator/config.go
insonmnia/locator/server.go
insonmnia/locator/server_test.go
locator.yaml
marketplace.yaml

This PR brings libkv support for the Locator. 
@3Hren @noxiouz @antmat PTAL

feature: add libkv support for Locator

---

insonmnia/structs/order.go

Changed:
- Keep internal protobuf order as an inclusion instead of private field.

fix: order serialization

---

insonmnia/hub/whitelist.go

fix: whitelist nil map

---

insonmnia/miner/server.go

As the status of tasks on Hub requires some time to
synchronize and a task might be killed during TaskListing,
we should not request metrics of the container.

fix: TaskList failed as there is no metrics for a killed container

---

cmd/cli/commands/interactor.go
cmd/cli/commands/tasks.go
insonmnia/hub/server.go
insonmnia/node/tasks.go

fix: do not cancel context for styreaming TaskLogs handle

---

insonmnia/node/server.go

fix: use WalletAuthenticator to check incoming requests into the Node

---

hub.yaml
insonmnia/hub/cluster.go
insonmnia/hub/config.go

feat: optional custom hub announce endpoint

---

cmd/cli/commands/printers.go
insonmnia/hub/server.go

fix: do not show error if device properties is not set

---

cmd/cli/commands/tasks.go
insonmnia/hub/server.go
insonmnia/node/server.go
insonmnia/node/tasks.go
task.yaml

@noxiouz @3Hren PTAL
* Make Logs, Pull Push authenticzted and working
* Add some more logs

fix: stream methods auth

---

.travis.yml
debian/control
debian/rules

Add ocl-icd-opencl-dev to build/install depends

debian: enable GPU_SUPPORT for packages

---

insonmnia/hub/eth.go
insonmnia/hub/server.go
insonmnia/structs/order.go
util/util.go

Added:
- Assertion during propose deal that bid.Price >= ask.Price.
- Assertion during propose deal that buyer has enough money and allowance to have a deal.
- Assertion before accepting a deal that deal price equals bid order price.

feat: more buyer verification

---

insonmnia/hub/server.go
insonmnia/hub/whitelist.go
insonmnia/hub/whitelist_test.go
insonmnia/miner/server.go

* Added whitelist test
* Do not make default user privileged if superusers are specified
* Extend taks status lifetime
* Do not return error on hub.TaskList

fix: wl tests, larger status cleanup period, proper tasks list

---

insonmnia/hub/server.go

fix: proper image tagging in pull

---

insonmnia/node/market.go

N.B.: please review this carefully.

fix: CancelOrder now stops processing loop

---

insonmnia/hub/miner_ctx.go
insonmnia/hub/router.go
insonmnia/hub/router_linux.go
insonmnia/hub/router_nonlinux.go
insonmnia/hub/server.go

This PR improves router interface by allowing to register several real services under the same virtual service.
Thus, we're almost ready to perform L3 load balancing IPvN->IPvM routing in any combination.

feat: improve router by allowing several reals

---

insonmnia/miner/overseer.go
insonmnia/miner/server_test.go

fix: do not uppercasing the env var keys

---

blockchain/api.go

fix: gas price for closing deal

---

util/util.go
util/util_test.go

This PR fixes an IP address checking from #381

fix: check if IP is loopback or unicast

---

insonmnia/hub/eth.go
insonmnia/hub/eth_test.go
insonmnia/hub/server.go

This PR fixes deal approving on the Hub side; Using the `WaitForDeal Created ` retriever to get a Deal or die with a timeout.
Also, refactored the `ETH` interface to use more convenient types.

fix: looking for created deal with given ID

---

.ci/coverage.sh
.gitignore
.travis.yml
Makefile
README.md

Added:
- Coverage
Changed:
- Parallelize builds.

feat: customize CI

---

insonmnia/node/hub.go
insonmnia/node/market.go
insonmnia/node/market_test.go

This PR adds the cancellation for deals, that was not approved on the Hub. 
Closes DEV-354

fix: cancel unapproved deal

---

insonmnia/structs/resources.go
insonmnia/structs/resources_test.go

This PR fixes allocating containers without CPU restrictions.

fix: properly allocate CPUs in tasks

---

cmd/cli/commands/printers_test.go

This PR fixes broken master ¯\ (ツ)/¯

fix: add version placeholder for tests

---

hub.yaml
insonmnia/hub/cluster.go
insonmnia/hub/config.go
insonmnia/hub/config_test.go
insonmnia/hub/server.go
insonmnia/miner/options.go
insonmnia/miner/server.go
insonmnia/miner/server_test.go

This PR makes workers connect to all known hubs. When a hub dies, worker forgets about the hub.

fix: miner connects to all hubs

---

insonmnia/hub/orders.go
insonmnia/hub/server.go

fix: proper order restoration

---

accounts/keys.go
cmd/cli/config/config.go
insonmnia/hub/miner_ctx.go
insonmnia/miner/cgroup.go

chore: fixed grammar

---

cmd/node/main.go
insonmnia/hub/cluster.go

chore: fixed logging levels

---

hub.yaml
insonmnia/hub/cluster.go

Refactoring + increased announcement period.

chore: cluster refactoring

---

README.md

docs: update readme for v0.3.1

---

cmd/cli/commands/hub_order.go
cmd/cli/commands/market.go
cmd/cli/commands/tokens.go
util/util.go
util/util_test.go

changed:
- allow a user to pass price in Ether units instead of Wei units via CLI;

feature: present prices as Ethereum-compatible values

---

debian/control
debian/rules
debian/sonm-cli.bash-completion

feat: bash completion in deb

---

Makefile
debian/changelog

version: bump - 0.3.2

---

insonmnia/hub/slot.go

subj @3Hren @sshaman1101 @oopcode PTAL

refact: better logging for ask-plan processing

---

cmd/cli/task_config/config.go
cmd/cli/task_config/config_test.go

deleted:
- resources definition from task.yaml and taskConf interface
- tests for resources parsing
added:
- tests for volumes and mounts definition

chore: remove useless task parameters

---

insonmnia/miner/network/tinc_config.go
insonmnia/miner/network/tinc_driver.go

@oopcode @sshaman1101 @3Hren PTAL

feat: store tinc plugin data in boltdb

---

insonmnia/hub/state.go

changed:
- Use `state.tasks` to provide tasks list, ask Workers for actual task details.
- Do not use `ID` field of the `task` struct with an undefined state.

fix: improve Hub's tasks state

---

insonmnia/hub/server.go

I am sick and tired of having to Ctrl+F for Hub's constructor all the time (and finding it somewhere around the 870-th line). Please do not resist.

chore: moved hub constructor closer to hub definition

---

insonmnia/npp/puncher.go

fix: updating goroutine spawning because of vet is not happy

---

task.yaml

fix: update task.yaml example with tinc network spec

---

insonmnia/node/config.go
insonmnia/node/market.go
insonmnia/node/market_test.go
insonmnia/node/server.go
util/rest/aes.go
util/rest/options.go
util/rest/server.go

Rest interface for Node.
@3Hren @sshaman1101 @oopcode PTAL

feat: REST interface for node

---

etc/relay.yaml
insonmnia/npp/relay/config.go
insonmnia/npp/relay/monitor.go
insonmnia/npp/relay/server.go

Now Relay monitoring server communicates using TLS.

feat: secure monitoring for relay

---

insonmnia/npp/puncher.go

This commit fixes a timeout triggered when an successful connection through a Rendezvous was discarded because of wrong logic that require to wait all other connections either become established or failed.
Also fixed a misleading logging message saying that a connection is failed to be established even if it's not true.

fix: immediately return the first RV connect

---

insonmnia/npp/relay/server.go

fix: relay maybe incomplete read write

---

proto/insonmnia.go

feat: unwrap for data size proto struct

---

cmd/cli/commands/client.go
cmd/cli/commands/common.go
cmd/cli/commands/deals.go
cmd/cli/commands/market.go
cmd/cli/commands/tasks.go
cmd/cli/commands/worker.go
cmd/cli/commands/worker_askplans.go
cmd/cli/commands/worker_devices.go
cmd/cli/commands/worker_tasks.go
insonmnia/node/config.go
insonmnia/node/server.go

This PR returns back secure connection between CLI and Node.
Flags for disabling TLS added to the Node's config and to the
CLI as `--insecure` parameter.

feat: client connect encryption

---

insonmnia/benchmarks/benchmarks.go

fix: proper benchmarks IDs

---

blockchain/api.go
insonmnia/node/market.go

Better async interface for blockchain API
@oopcode @sshaman1101 @quasisamurai  PTAL

refact: better BC API

---

insonmnia/miner/network/l2tp_state.go

Not so useful, but I need to warmup :)

refact: l2tp_state reduce allocations

---

cmd/dwh/main.go
etc/dwh.yaml
insonmnia/dwh/config.go
insonmnia/dwh/server.go
insonmnia/dwh/sql.go

DWH now serves both gRPC and HTTP requests.

feat: added REST support to DWH

---

cmd/dwh/main.go
insonmnia/dwh/server.go

* retry for failed events
* proper context handling

feat: dwh event fallback and proper contexts

---

insonmnia/dwh/server.go

chore: dwh refactoring

---

cmd/pandora/ammo_marketplace.go
cmd/pandora/common.go
cmd/pandora/config.go
cmd/pandora/gun_marketplace.go
etc/pandora.yaml

Also orders with-real benchmarks are placed.

feat: massive order placing

---

insonmnia/dwh/server.go
insonmnia/dwh/sql.go

Defer statement captures err above the defer statement.
if := (unlike =) redefines a new err var, not one captured by defer.
https://play.golang.org/p/aRfM6NSl98t

dwh: fix cleaning setupSQLite

---

vendor/vendor.json

@3Hren @noxiouz @sshaman1101 PTAL

fix: vendoring

---

proto/bigint.go
proto/bigint_test.go

@noxiouz @3Hren @oopcode @sshaman1101  PTAL

refact: use text (un)marshallers for BigInt

---

vendor/gopkg.in/yaml.v2/NOTICE
vendor/gopkg.in/yaml.v2/README.md
vendor/gopkg.in/yaml.v2/apic.go
vendor/gopkg.in/yaml.v2/decode.go
vendor/gopkg.in/yaml.v2/emitterc.go
vendor/gopkg.in/yaml.v2/encode.go
vendor/gopkg.in/yaml.v2/go.mod
vendor/gopkg.in/yaml.v2/readerc.go
vendor/gopkg.in/yaml.v2/resolve.go
vendor/gopkg.in/yaml.v2/scannerc.go
vendor/gopkg.in/yaml.v2/sorter.go
vendor/gopkg.in/yaml.v2/writerc.go
vendor/gopkg.in/yaml.v2/yaml.go
vendor/gopkg.in/yaml.v2/yamlh.go
vendor/vendor.json

More details on https://github.com/go-yaml/yaml/pull/256.

fix: yaml marshalling

---

blockchain/api.go
insonmnia/node/deals.go

@Sokel @sshaman1101 @quasisamurai @oopcode PTAL

refact: wait for close deal tx to be mined

---

blockchain/examples/placeOrder/placeOrder.go

* update blockchain submodule:
* market already has QuickBuy function
* fix benchmarks max capability
* fix SNMT dependency
*  fix orderPlace example

upd: redeploy blockchain contracts

---

insonmnia/hardware/hardware.go
insonmnia/miner/server.go
proto/ask_plan.go

Open chakras @3Hren @sshaman1101 don't take a look, just test this shit

fix: pass GPU ids to overseer

---

insonmnia/miner/server.go

fix: allocate all GPU if it is not specified in task

---

insonmnia/miner/salesman.go
insonmnia/miner/server.go
proto/insonmnia.go

subj. @3Hren @sshaman1101 PTAL

fix: listen for closed deals in worker

---

proto/ask_plan.go

fix: proper GPU normalization

---

ask.yaml
bid.yaml
cmd/cli/commands/printers.go
proto/ask_plan_test.go
proto/bigint_test.go
proto/insonmnia.go
proto/insonmnia_test.go

fix: use USD prices

---

insonmnia/dwh/postgres.go
insonmnia/dwh/server.go
insonmnia/dwh/sqlite.go
proto/ask_plan.go

Old version only updated payout for deal conditions, this PR adds updates for corresponding deals.
(P.S. And missed mutex Lock/Unlock).

fix: update deal total payout (DWH)

---

insonmnia/miner/server.go

fix: release resources on broken tasks too

---

insonmnia/miner/salesman.go

This PR removes situation when expired deal is billed and then closed. This achieved with rather little blood, so I suggest to merge in consensus branch too

fix: first check if deal should be closed

---

cmd/cli/commands/tasks.go
insonmnia/auth/addr.go
insonmnia/hardware/hardware.go
insonmnia/hub/acl.go
insonmnia/miner/network/tinc_network.go
insonmnia/miner/network/tinc_state.go
insonmnia/miner/plugin/plugin.go
insonmnia/miner/salesman.go
insonmnia/miner/server.go
insonmnia/node/deals.go
insonmnia/node/market.go
insonmnia/node/server.go
insonmnia/node/tasks.go
insonmnia/resource/pool.go
util/netutil/net.go
util/rest/server.go

Slightly more informative errors in cli
@sshaman1101 @oopcode @3Hren PTAL

fix: better errors in deals API

---

insonmnia/hardware/hardware.go

I don't know how to emulate optionals in a better way, but they are needed for min summarizing algo.
@sshaman1101 @oopcode @3Hren PTAL

fix: use gostyle optional for benchmarks

---

insonmnia/miner/config.go
insonmnia/miner/salesman/options.go
insonmnia/miner/salesman/salesman.go
insonmnia/miner/server.go

* Salesman uses options for configuration. 
* Config introduced for fine tuning and hard-code removal
* Use timer instead of ticker for excluding subroutine working time
@sshaman1101 @oopcode @3Hren PTAL

feat: salesman options and config

---

Makefile
cmd/cli/commands/common.go
cmd/cli/commands/version_test.go
cmd/cli/config/config.go
cmd/cli/config/config_test.go

This is needed to save some current context on the fly - such as default address, current worker address, or smth else
@sshaman1101 @oopcode @3Hren PTAL

feat: ability to save cli config

---

blockchain/api.go
blockchain/client.go
blockchain/examples/customClient/customClient.go
blockchain/examples/getBlockNumber/getBlockNumber.go
blockchain/examples/placeOrder/placeOrder.go
blockchain/examples/placeOrder/placeOrderNew.go
blockchain/options.go
blockchain/util.go

* add utils that await block confirmation
* upd PlaceOrder & OpenDeal funcs
* add custom ethclient

 feat: transaction confirmation awaiting

---

insonmnia/hardware/hardware.go
insonmnia/worker/server.go

@3Hren @sshaman1101 @oopcode PTAL
I doubt that this API looks ok , so this is done for existing bot compatibility. IMO we should rework this in future.

feat: free devices for autosell bot

---

insonmnia/node/tasks.go

refactor: drop dead code

---

insonmnia/hardware/hardware.go

fix: off by one error - proper slice size

---

insonmnia/npp/dial.go

This commit allows to specify a context while dialing using NPP.

feat: dial context for NPP

---

cmd/cli/commands/common.go
cmd/cli/commands/master.go
cmd/cli/commands/tasks.go

refactor: remove boilerplate

---

insonmnia/worker/container.go
insonmnia/worker/overseer.go
insonmnia/worker/server.go

This PR sycnhronizes tasks lifetime with deal lifetime, performing needed cleanup when deal is closed.

refactor: tasks lifetime

---

etc/optimus.yaml
optimus/config.go
optimus/optimus.go

 refactor: decompose benchmarks for autosell bot

---

cmd/cli/commands/worker.go

This PR introduces interactive worker switching in cli.

refactor: interactive worker switching

---

insonmnia/worker/salesman/salesman.go

Do not block on salesman startup and run it in background.
Still need to refactor matcher, as it requires full order, resulting in request to blockhain, so it is hotfix.
@3Hren @sshaman1101 @oopcode PTAL

fix: slow start

---

blockchain/source/scripts/test.sh
blockchain/source/truffle.js

Change testrpc port from `8545` to `8535`.

chore: change testrpc port

---

cmd/cli/commands/worker.go
insonmnia/npp/dial.go

subj + writing warning to log when it is impossible to use direct addr

fix: proper worker address parsing

---

blockchain/source/addresses.go
blockchain/source/migrations/1_deploy_token.js
blockchain/source/migrations/2_deploy_oracle.js
blockchain/source/migrations/3_deploy_SimpleGatekeeper.js
blockchain/source/migrations/4_init_gatekeeper.js

Add migrations scripts for deploying contract and file where addresses of deployed contract placed.

feat: add deploy suite

---

blockchain/source/addresses.go
blockchain/source/deployed/contracts/BasicToken.json
blockchain/source/deployed/contracts/ERC20.json
blockchain/source/deployed/contracts/ERC20Basic.json
blockchain/source/deployed/contracts/Migrations.json
blockchain/source/deployed/contracts/OracleUSD.json
blockchain/source/deployed/contracts/Ownable.json
blockchain/source/deployed/contracts/SNM.json
blockchain/source/deployed/contracts/SNMD.json
blockchain/source/deployed/contracts/SNMTToken.json
blockchain/source/deployed/contracts/SafeMath.json
blockchain/source/deployed/contracts/SimpleGatekeeper.json
blockchain/source/deployed/contracts/StandardToken.json

* Deploy SNMD at sidechain.
* Deploy SimpleGatekeeper to rinkeby chain.
* Deploy SimpleGatekeeper to sidechain.
Saving json artifacts of deployed contracts is necessary.

aux: redeploy contracts

---

cmd/cli/commands/worker.go
cmd/cli/commands/worker_devices.go
insonmnia/hardware/hardware.go
insonmnia/hardware/hardware_test.go

* free devices handle in cli
* proper benchmarks collecting resulting in proper FreeDevices functionality

fix: benchmark proper collecting

---

blockchain/api.go

New version of contract change logs format for `Billed`, `OrderBlaceTopic` topics.
Now its doesn't need to be decoded with ABI.

fix: malformed topic format

---

insonmnia/worker/container.go
insonmnia/worker/overseer.go

chained with #871 
This PR adds external context for all operations with container. 
This fixes that container can not be deleted due to context cancellation after deal is closed.

fix: container ctx

---

blockchain/api.go
blockchain/util.go

fix blockchain:
* do not fetch inconsistent orders and deals
* do not use pending state for querying

fix: blockchain ne bolei

---

etc/node.yaml
etc/optimus.yaml
etc/pandora.yaml
etc/worker.yaml

subj, ns names can be unassigned right now

refactor: release configs

---

debian/changelog

* Added: NAT punching.
This adds the full NAT Punching Protocol implementation, allowing to
connect Hub and its clients, including workers, even if they are located under
a single or several NATs.
Also this commit adds a Rendezvous server, which acts as an intermediate
metadata exchange point.
NPP is a protocol aimed to achieve mutual address resolution for both client
and server. This is especially useful where there is no guarantee
that both peers are reachable directly, i.e. behind a NAT for example.
The protocol allows for servers to publish their private network addresses
while resolving their real remove address. This information is saved under
some ID until a connection held and heartbeat frames transmitted.
When a client wants to perform a connection it goes to this server, …

version: bump - 0.4.0-alpha1

---

blockchain/source/contracts/Market.sol
blockchain/source/test/market.js

Fixed incorrect work of QuickBuy func

fix: QuickBuy bug

---

.mailmap

chore: update mailmap

---

blockchain/api.go
blockchain/config.go
blockchain/options.go

Rename 'livechain' to 'masterchain'

chore: rename ambigious name in opts

---

insonmnia/worker/container.go
insonmnia/worker/overseer.go

Going to use to maintain limits for a deal (like storage space)

feat/overseer: mark containers with deal ID

---

blockchain/api.go
blockchain/examples/placeOrder/placeOrder.go

Use common address instead of string.
Repair example as related.

chore: simplify allowance method

---

blockchain/api.go
insonmnia/dwh/config.go
insonmnia/dwh/server.go

This PR makes use of `CustomEthereumClient`'s `GetLastBlock()` method to automatically determine when to build indices in cold start mode.

feat: coldstart auto block number (DWH)

---

blockchain/api.go

Add interface and bindings to BasicAPI.

feat: add SimpleGatekeeper blockchain api

---

insonmnia/dwh/sql.go

GetMasterByWorker now returns only confirmed masters.

fix: GetMasterByWorker returns confirmed workers (DWH)

---

blockchain/api.go
blockchain/util.go

Remove old await func for consistency.
New function works with confirmationa and returns receipt instead of one undefined transaction log.
PS: uniform any parts with awaiting for consistency

refactor: use await with confirmations instead of old func

---

blockchain/api.go
blockchain/examples/placeOrder/placeOrder.go
blockchain/types.go
cmd/pandora/ammo_marketplace.go
insonmnia/matcher/matcher.go
insonmnia/matcher/matcher_test.go
insonmnia/node/deals.go
insonmnia/node/market.go
insonmnia/node/master.go
insonmnia/worker/salesman/salesman.go
insonmnia/worker/server.go

Remove abuse returning channels in blockchain api.
Ps: everywhere it was used synchronously.

chore: remove abuse async

---

optimus/devices.go
optimus/devices_test.go
optimus/optimus.go

This PR fixes a bug where a minimum number of some criteria (for example)RAM was too low than the minimum one by one. This is caused by loosing precision while converting to float64 and vice-versa - fixed by ceiling the result.
Also found and fixed a bug which caused the Optimus to overcut celling plans, because of invalid math - I used current benchmarks for calculating relational criteria, while lower bounds are calculated against total devices. Now we use initial benchmarks for this case.

fix: Optimus should now properly cut minimum RAM

---

blockchain/api.go
blockchain/options.go
blockchain/util.go

Move getTxOpts() function to chain options.
I know that this should be here.

refactor: move getTxOpts to chainopts

---

blockchain/source/contracts/Market.sol

Tis a common protection from overflow.

fix: rework all arithmetics to safe

---

blockchain/source/contracts/Market.sol

This pr fixes a big bug while market refund least funds, that eq to blocked.balance before Bill. It also refunded to master, not to consumer 
chained:  #989

fix: incorrect billing

---

blockchain/api.go

Add increase/decrease token functions.
PS: 1 line affected by `fmt`

feat: increase/decrease approval

---

optimus/learning.go
optimus/optimus.go
optimus/structs.go

This commit allows autosell bot to predict its price based on previous learning iteration.
It is required for further canceling orders depending on its predicted market price.
Also this change adds MUCH more verbose logging to be able to debug it somehow.

feat: optimus price prediction

---

insonmnia/dwh/server.go
util/util.go

chore: also remove laconic error

---

insonmnia/npp/relay/server.go

At some point we disabled clients queuing for Relay, but some dead was left; this PR removes it.

chore: removed dead code in relay

---

optimus/config.go
optimus/optimus.go

Since now Optimus can sell only for spot deals, with zero duration.

feat: spot-only orders for Optimus

---

blockchain/source/contracts/Market.sol

This feat impements destroying of contract. It also returns all frozen funds to owner (multisig).
Needs to prevent funds locking while some bug found.

feat: kill option for market contract

---

.github/CODEOWNERS

As developer, i'm the author of lot of files in this folder. Also someone should rewiev every sokel's PR.
:pig:

chore: add me to as code owner for blockchain folder

---

insonmnia/state/state.go
insonmnia/worker/options.go
insonmnia/worker/overseer.go
insonmnia/worker/salesman/salesman.go
insonmnia/worker/server.go
proto/capabilities.go

This PR allows worker to perform and cache benchmarks separately for each device
and  enables parallelized benchmarks for GPU

refactor: flexible benchmarks

---

etc/optimus.yaml
optimus/config.go
optimus/math.go
optimus/optimus.go
optimus/registry.go

Now all required components like Worker, DWH, marketplace etc. are placed in a special component - registry. It manages certificates, capable to close them and at last is able create those components.
Also this change allows to create multiple worker clients with different account settings.

refactor: decompose components logic in Optimus 

---

insonmnia/worker/gpu/dri.go
insonmnia/worker/gpu/dri_unix.go
insonmnia/worker/gpu/dri_windows.go

fix: build DRI module on non-unix

---

optimus/learning.go
optimus/optimus.go

Previously a quite complicated motivation was used to calculate order weights. It was hard to understand, and een harder to debug.
Now we use a simple predictedPrice/price as a criteria of order's attractiveness.

refactor: simplify weight formula in Optimus

---

optimus/optimus.go
optimus/registry.go

Accidentally we used gRPC API to the DWH instead of blockchain API.

fix: use proper market API in Optimus

---

insonmnia/resource/pool.go

This PR fixes segfault due to uninitialized log field in Scheduler

fix: proper log field initialization

---

blockchain/addresses.go
blockchain/api.go
blockchain/config.go
blockchain/examples/placeOrder/placeOrder.go
blockchain/options.go
cmd/pandora/gun_marketplace.go
insonmnia/dwh/server.go
insonmnia/node/server.go
insonmnia/node/server_test.go
insonmnia/node/tokens.go
insonmnia/worker/options.go
insonmnia/worker/salesman/salesman.go
optimus/optimus.go

This PR replaces static smart contract addresses with contract registry smart contract, whichh is loaded on start and caches all addresses.

feat: contract registry

---

optimus/optimus.go

This fixes a bug when Optimus inproperly filtered already existing ask-plans, which led to its duplication.

fix: proper order cancel and create

---

optimus/optimus.go

Chained with #1114, so merge it first.

refactor: save some lines of code

---

Makefile
blockchain/addresses.go
blockchain/api.go
blockchain/topics.go
blockchain/types.go
cmd/oracle/main.go
etc/oracle.yaml
insonmnia/dwh/server.go
insonmnia/oracle/config.go
insonmnia/oracle/oracle.go
insonmnia/oracle/watcher.go

Add Oracle script;
This implementation works through MultiSig contract.
For prevent races it have two modes:
- In master mode script submitting price change to multisig
- In slave mode script listen submitting from master, verify price, and confirm it.
Any mode script have price watcher, for timely update SNM-USD price.
Watcher loads data from cmc SNM ticker.
chained with #1069

feat: oracle

---

Makefile
debian/control
debian/rules
debian/sonm-oracle.default
debian/sonm-oracle.install
debian/sonm-oracle.service

aux: oracle debianization

---

blockchain/api.go
blockchain/source/api/SimpleGatekeeperWithLimit.go
blockchain/source/api/SimpleGatekeeperWithLimitLive.go

fix: cli deposit

---

blockchain/api.go
blockchain/config.go
blockchain/options.go
etc/dwh.yaml
insonmnia/dwh/server.go
insonmnia/oracle/oracle.go

still WIP, tried to make a bit more clear replacement for #1158

refactor: events api

---

cmd/cli/commands/client.go
cmd/cli/commands/common.go
cmd/cli/config/config.go

Let's specify the node we want to connect to in cli's config:
```
node_addr: localhost:15555
```

feat: Adds node_addr config variable to cli

---

insonmnia/npp/listener.go

Fixes bug introduced in #1189.

fix: using nil variable

---

insonmnia/npp/listener.go

Unfortunately, when stopping gRPC server it is required the underlying listener to return from its "Accept" call. We can't guarantee this, however, because it doesn't use "AcceptContext", which is capable of doing this.
This commit allows to close NPP listener by keeping cancellation context in it. Yep, this sucks.

fix: worker hanging

---

blockchain/types.go
blockchain/types_test.go
blockchain/unit.go

Use in #1195 with pleasure, Luke.

feat: ETH units

---

cmd/optimus/main.go
optimus/engine.go
optimus/optimus.go
optimus/options.go
optimus/tagging.go
proto/marketplace.go

Now Optimus will assign its tag with version to ask plans created.

feat: assign tags in Optimus orders

---

insonmnia/dwh/sql.go

Dropping `sqlite3` lets us rewrite some blatantly disgusting parts of DWH sql-related code (namely, we can now use `ON CONFLICT DO UPDATE/NOTHING` statements).

chore: optimized SQL (DWH)

---

insonmnia/dwh/sql.go

This PR fixes the `HasActiveChangeRequests` status for DWH deals.

fix: hasActiveCR status for deals (DWH)

---

cmd/cli/commands/printers.go

This fixes the previous ask-plan printing behaviour where the "tag" field was printed as a byte array, which is not human-readable.
This is done via type erasure hack with reflection. The only reason this is done this way is not to break the backward compatibility.
I wish there is another cleaner way.

fix: print ask plan tags as strings

---

optimus/model.go
optimus/model_nnls.go

This adds a new more-physically-correct optimization method - the non-negative multidimensional linear least squares (NNLS).
It constraints the result vector values to be a non-negative, which in its turn means that each of them will show to the real benchmark price per basis.
Also this shows an extremely performance boost - million of orders are optimized in less than for a second.
However, currently this is an experimental proposal.

feat: non-negative LLS solver for Optimus

---

bid.yaml

more descriptive bid specification

fix: comments in bid config

---

connor_v2/antifraud/antifraud.go
connor_v2/antifraud/blacklist_watcher.go
connor_v2/antifraud/config.go
connor_v2/antifraud/logProcessor.go
connor_v2/engine.go
vendor/github.com/VividCortex/ewma/LICENSE
vendor/github.com/VividCortex/ewma/README.md
vendor/github.com/VividCortex/ewma/ewma.go
vendor/vendor.json

feat: antifraud

---

debian/sonm-connor.service

fix: proper Connor's binary path in systemd-unit

---

insonmnia/dwh/setup_test.go

This PR ensures that DB inside the container is ready for use when tests start to execute.

fix: postgres container setup

---

insonmnia/dwh/l1_processor.go
insonmnia/dwh/sql.go

Optimize worker insertion with `ON CONFLICT DO NOTHING`.

refactor: worker id conflicts (DWH)

---

optimus/engine.go

Now Optimus while being run under dry-run option will show removing candidates ask-plans.

refactor: tune dry-run in Optimus

---

connor/antifraud/antifraud.go
connor/engine.go

This commit adds prometheus metrics which gives us some info
about orders and deals lifespans.

feat: prometheus metrics for Connor

---

connor/engine.go

refactor: proper context usage in Connor's engine

---

connor/config.go
connor/engine.go
etc/connor.yaml

This commit moves all price control settings into a single section.

refactor: new price config for Connor

---

optimus/engine.go

Optimus should no longer create plans for its own asks.

fix: proper own ask filtering in Optimus

---

connor/config.go
connor/price/price.go
connor/price/price_test.go

This commit replaces incompleted ZEC's price provider with the XMR one.
Also, this commit replaces ZEC token with XMR_CPU in the config
(zec support wasn't completed at all).

feat: XMR price provider for Connor

---

blockchain/api.go
blockchain/api_ext.go
blockchain/api_ext_test.go
blockchain/options.go
insonmnia/node/remote.go
proto/marketplace.go

This commit activates special interceptor on Node that performs userland
verification before opening a deal. This allows to return human-readable
errors instead of "Transaction failed" in case of where it is impossible
for some reasons to open a deal.
<details>
<summary>Now it looks like this</summary>
<p>
```bash
esafronov@esafronov:~/go/src/github.com/sonm-io/core|feat/blockchain/wrap-market⚡
⇒  ./target/sonmcli_darwin_x86_64 deal open 152069 151941 --force
[ERR] cannot open deal: rpc error: code = Unknown desc = could not open deal in blockchain: ask order must be active, but it is ORDER_INACTIVE
esafronov@esafronov:~/go/src/github.com/sonm-io/core|feat/blockchain/wrap-market⚡
⇒  ./target/sonmcli_darwin_x86_64 deal open 152071 151941 --force
[ERR] cannot open deal: rpc error: code = …
```

feat: blockchain errors for humans

---

connor/engine.go

This commit moves a price calculation code into a `sendOrderToMarker` method,
it allows us to calculate the actual price on each order re-creation.
Also it fixes a bug when Connor replaces order on price deviation by an
order with absolute same parameters.

fix: proper order price setting in Connor

---

vendor/vendor.json

Related to #1043 and sshaman1101/grpccmd#1
No diff on code because vendored version was patched in #1043.

chore: sync vendored grpccmd package

---

insonmnia/worker/network/manager_linux.go

Currently, IFB devices aren't removed while ask-plans are being removed. This leads to something like this: 
After this commit, they should be properly removed.

fix: remove IFB dev on ask-plan remove

---

blockchain/api.go
insonmnia/worker/salesman/salesman.go

this PR enables parallel blockchain processing in salesman, which results in boost on massive ask-plan creation or purging.

perf: process blockchain in worker in parallel

---

insonmnia/worker/server.go

Currently at startup worker does not check deal status for tasks saved in boltdb. This PR makes worker kill and forget such tasks.

fix: kill tasks if deal was closed

---

insonmnia/worker/server.go

fix: proper deal id comparision

---

insonmnia/npp/dial.go

This commit fixes socket leakage in Node by draining pending channels in case of timeout errors.

fix: socket leak in Node

---

cmd/cli/commands/worker.go

this PR adds ability to specify custom worker address in cli to work with

feat: worker address flag for cli

---

insonmnia/worker/salesman/salesman.go

closes #1428
due to some strange circumstances (that could be possible if we received stale data from blockchain after deal registration, or failed to save data in boltdb) order could be removed before deal, resulting in neverending cycle of deal removal. This PR fixes this behaviour.

fix: unregister closed deal despite result of order deregistration

---

cmd/cli/commands/printers.go

fix: proper task tag printer

---

cmd/cli/commands/profiles.go

fix: proper error if profile doesn't exists

---

insonmnia/npp/rendezvous/server.go

Hope this helps to debug "and it's gone" bug in the Rendezvous server.

feat: log requests in Rendezvous

---

insonmnia/resource/pool.go
insonmnia/worker/server.go

this PR fixes bug, when deal was closed during task start and task was not released properly

fix: drop task if the deal was closed during start up

---

insonmnia/worker/container.go
insonmnia/worker/overseer.go
insonmnia/worker/overseer_test.go
insonmnia/worker/server.go
insonmnia/worker/whitelist.go
insonmnia/worker/whitelist_test.go
util/xdocker/reference.go

This PR adds handy reference wrapper to simplify it's usage and make proper serialization/deserialization

refactor: handy reference wrapper

---

cmd/cli/commands/printers.go

fix: show all balances when with output=JSON

---

cmd/cli/commands/printers.go

Closes #1489
```
» cli order list
ID  | TYPE |     TAG     |       PRICE        | DURATION
+------+------+-------------+--------------------+----------+
5282 | BID  | connor_mcpu | 0.0004195904457276 | spot
5279 | BID  | connor_mcpu |  0.000399609948312 | spot
5284 | BID  | connor_mcpu | 0.0004395709431432 | spot
5280 | BID  | connor_mcpu | 0.0004595514405588 | spot
5281 | BID  | connor_mcpu |   0.00049951243539 | spot
5283 | BID  | connor_mcpu | 0.0004795319379744 | spot
count: 6
```

chore: show tags in orders list

---

etc/dwh.yaml
insonmnia/dwh/processor.go
insonmnia/dwh/processor_test.go

the `CertificateUpdated` event was not processed (missing handler call), this PR fixes the issue

fix: activate onCertificateUpdated handler

---

connor/engine.go

Early we logging price-per-second-per-hash from the PriceProvider,
this commit replaces this value with full order price per second which
is more easy for future analysis.

fix: proper logging on price deviation

---

cmd/cobra.go

Previously if user specifies config path like `~/config/node.yaml`, service cmd wrapper wasn't threated `~` as home dir. This commit fixes this issue.

fix: always expand config path

---

cmd/cli/commands/printers.go
proto/bigint.go

fix: show change request price in USD/h

---

Makefile
cmd/cli/main.go
cmd/cobra.go

fix: proper version var for cli

---

insonmnia/npp/relay/server.go

Several weeks ago a new bug was introduced in Relay server - half of the remote peer sockets were leaked forever. This was because of improper synchronization during rendezvous point, where both remote server and client are met. So when a client did its job we closed only a server socket, not the client one and vise-verse.
This patch fixes such behavior - everything should work fine from now, at least with dead socket collection.
Closes #1566.

fix: socket leak in Relay

---

insonmnia/npp/relay/server.go

Do not block on meeting, while holding a lock.
Changelog: exclude

fix: relay asynchronously

---

optimus/market.go

We've reached gRPC frame size limit when fetching too many orders from the DWH. This commit applies paging to avoid this problem.

fix: chunked fetching orders in Optimus

---

insonmnia/worker/salesman/salesman.go

This PR fixes ask-plan removal which could fail due to improper check of placing concurrent order or/and inability to remove cgroup or network in case if ot even was not created

fix: properly remove ask plan

---

debian/sonm-mon.service

sonm-mon does not use sonmcli anymore.

fix: sonmmon should not depend on sonmcli

---

proto/optimus.go

feat: validate prediction request

---

optimus/context.go
optimus/engine.go
optimus/engine_branch.go
optimus/engine_genetic.go
optimus/engine_greedy.go
optimus/engine_multi.go

Now Optimus can stop its optimization process if a caller no longer awaits for the result.

feat: teach Optimus to cancel optimization

---

connor/antifraud/config.go
connor/antifraud/pool_processor.go
connor/antifraud/pool_processor_test.go
etc/connor.yaml

Idea is very similar to the `commonLogProcessor`.
This commit extracts common parts from pool processor into reusable structure. Now we can easily add new pools only by implementing the `updateFunc` function.

feat: common pool processor for anti-fraud

---

cmd/cli/commands/deals.go
cmd/cli/commands/printers.go
cmd/cli/commands/printers_test.go

feat: show hourly expenses for deals

---

optimus/engine.go
optimus/engine_axe.go

This is the model from the winner of our Programming Challenge.

feat: add axe optimization model

---

optimus/engine.go

fix: compare only victim price in Optimus

---

optimus/market.go

While we're having constantly increasing the number of deals it may appear, that fetching the entire data set of deals can overflow the allowed gRPC response size.
This commit fixes that behavior by fetching deals chunked.

fix: chunked deals fetching in Optimus

---

insonmnia/worker/overseer.go

fix: set proper status on container exit

---

connor/antifraud/pool_processor.go
connor/antifraud/processor.go
connor/config.go

This commit adds new pool processor for Connor's antifraud system.
Can be enabled using `antifraud.pool_processor.format: uley` option.

feat: pool processor for UleyPool

---

optimus/devices.go

This suddenly gives about x100 performance booth in the "consumeGPU" method.
The overall performance has been increased in ~2 times.

perf: cache benchmarks meta in Optimus

---

optimus/devices.go
optimus/devices_test.go

perf: cache GPU benchmarks in Optimus

---

insonmnia/worker/gpu/nvidia_tuner.go

Fixes a situation when nvidia drivers was updated, but docker knows about the volume with the previous version of drivers. Now the plugis will obtain driver version and create new volume if it does not exists.

fix: proper version for nvidia plugin

---

insonmnia/worker/options.go
insonmnia/worker/ssh.go

This PR allows to specify untrusted and leaked ETH addresses that are not allowed to be used for remote SSH login. This includes our public test key, that is widely used for testing. More can be specified in Worker's config.

feat: SSH keys management

---

blockchain/source/contracts/SimpleGatekeeperWithLimit.sol
blockchain/source/contracts/SimpleGatekeeperWithLimitLive.sol

cleanup gate funcitons with language/linter specs

aux: cleanup gates warning

---

blockchain/source/contracts/SimpleGatekeeperWithLimit.sol
blockchain/source/test/simpleGatekeeperWithLimit.js

feat: add PayoutTargeted to SimpleGatekeeper

---

insonmnia/worker/salesman/salesman.go
insonmnia/worker/server.go

This PR fixes the bug when worker forgets about his tasks on restart

fix: properly restore worker state on restart

---

insonmnia/dwh/processor.go
insonmnia/dwh/sql.go

deal payments were not recorded to db for some reason, this PR fixes it

fix: record deal payments (DWH)

---

util/ticker.go

Eliminate variable name collision. Also some refactoring shit applied.

refactor: code eye-candy for immediate ticker

---

.gitignore
blockchain/source/package-lock.json

this PR locks all npm deps resulting in a more stable behaviour

fix: lock npm deps

---

util/xgrpc/client.go

fix: master

---

insonmnia/worker/salesman/salesman.go

This PR fixes error durng removal of ask-plan on startup due to resource change

fix: proper ask-plan removal on startup

---

util/xnet/quic.go

Right now all gRPC servers are stopped when they receive a non-temporary error from the acceptor socket. Unfortunately, after introducing QUIC we forgot to check whether this invariant is true, and now we suffer from servers termination on any QUIC timeout etc.
This patch should fix random server stopping during some kind of temporary network problems.

fix: no not stop gRPC servers on temporary QUIC errors

---

insonmnia/worker/gpu/nvidia_tuner.go

If worker terminates unexpectly, it leaves an orphaned socket file made by the NVidia GPU plugin.
In such case the systemd cannot restart worker because  of "address already in use" error. So we should remove this socket when initializing new listener for the GPU plugin.

fix: drop nvidia socket if exists

---

blockchain/source/migration_utils/multisig.js
blockchain/source/migrations/2_deploy_v1.js
blockchain/source/migrations/3_deploy_devices_storage.js

subj, now we use the proper multisig contract

fix: migration with proper multisig

---

insonmnia/worker/gpu/radeon_tuner.go

Now I know how to make a slice of pointers
from the slice of values.
More on this
https://github.com/golang/go/issues/22791#issuecomment-345391395
Closes #1811

fix: proper processing for collected DRI devices

---

cmd/cli/commands/tokens.go

chore: set deposit/withdraw amount in SNM instead of wei 

---

cmd/dwh/main.go
insonmnia/dwh/config.go

feat: configurable pprof for DWH

---

cmd/cli/commands/worker.go

Exposed an ability to watch Worker's config for its admin, master and inspection subjects.

feat: worker config command

---

cmd/cli/commands/printers.go
insonmnia/benchmarks/benchmarks.go
insonmnia/worker/server.go
proto/marketplace.go

this PR adds benchmarks for GPU type - nvidia or amd only, which is usefull when specific card type is required.

feat: benchmark support for GPU type

---

etc/optimus.yaml

Sensible defaults for brute-force optimisation

---

optimus/engine.go
optimus/predictor.go

6!=720, which is not so big as 16!=20 922 789 888 000.

fix: reduce fucking brute-force threshold for predictor

---

cmd/cli/commands/printers.go
proto/marketplace.go

merge with https://github.com/sonm-io/benchmarks-list/pull/16

chore: print cuckaroo29 benchmark in CLI

---

optimus/engine.go

Stop ignoring filters in Optimus in entire machine lease mode.

fix: stop ignoring filters in Optimus

---

insonmnia/worker/salesman/salesman.go

This one need to be tested. Also there is still also a probability to get `alien` order which need to be fixed in blockchain API in general, not the salesman

fix: temp fix for `alien` deals bound to ask-plans
